---
title: "GDP_Prem_Tests"
author: "Nathan Barretto"
date: "2024-05-19"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
library(tidyverse)
#importing the two datasets: GDP data and Veronesi data 
proxy_data <- read_csv("data_policycle.csv")
gdp_data <- read_csv("USGDP.csv")
combined_data <- merge(proxy_data, gdp_data)

```



```{r}
#invert rows and columns for gdp dataset
#source: https://stackoverflow.com/questions/33643181/how-do-i-flip-rows-and-columns-in-r
gdp_data_2 <- data.frame(t(gdp_data[-1]))
colnames(gdp_data) <- gdp_data[, 1]
```

```{r}
#rename columns in proxy dataset

#first column name changed to year_month
colnames(proxy_data)[1] <- "quarter_year"

```

```{r}
#adjust column names in gdp dataset to get the names of the columns to be that 
#of the first row names

for (x in 3:38) {
  name <- gdp_data_2[1,x]
  name_string <- toString(name) 
  colnames(gdp_data_2)[x] <- name_string
}
```


```{r}
#Adjust column names in proxy and gdp data to accurately reflect measurements
colnames(proxy_data)[67] <- "DPRatio"
#one-year equity premium bound proposed by Ian Martin in 2017
colnames(proxy_data)[70] <- "EP_Bound"
colnames(proxy_data)[47] <- "IPO_Gross"
colnames(proxy_data)[75] <- "Price_Volatile_Stocks"
colnames(proxy_data)[69] <- "Surplus_Cons_Ratio"
colnames(proxy_data)[76] <- "Agreggate_Risk_Aversion"
colnames(proxy_data)[19] <- "Unemployment_Rate"
colnames(gdp_data_2)[5] <- "GDP"
```


```{r}
#delete row 1 of gdp_data with the old names
gdp_data_2 <- gdp_data_2[-c(1), ]

```

```{r}
#delete first 2 columns of gdp_data
#Blank cells
gdp_data_2 <- gdp_data_2[ -c(1,2) ]
```



```{r}
#split proxy_data by quarter and year

#quarter makers function
quarter_makers = function(mths){
 q1_Vector <- c(1, 2, 3)
 q2_Vector <- c(4, 5, 6)
 q3_Vector <- c(7, 8, 9)
 q4_Vector <- c(10, 11, 12)
 
 result <- c()
 
 for(i in 1:length(mths)){
  if (mths[i] %in% q1_Vector ){
    result[i] <- "Q1"
  }
  else if (mths[i] %in% q2_Vector ){
    result[i] <- "Q2"
  }
  else if (mths[i] %in% q3_Vector ){
    result[i] <- "Q3"
  }
   else {
    result[i] <- "Q4"
   }
 }
 
 return (result)
}

```



```{r}
#Generate split of quarter and years using quarter makers function
proxy_data$months = as.numeric(substr(as.character(proxy_data$quarter_year),5,6))
proxy_data$Year = as.numeric(substr(as.character(proxy_data$quarter_year),1,4))
proxy_data$Quarter = quarter_makers(proxy_data$months)
```

```{r}
#download hmisc package
#install.packages("Hmisc")
#install.packages("acepack")
```


```{r}
#Modify both datasets so they include the same quarters from 1960 - 2015
#results in same dimensions for statistical analysis later
proxy_data_mod_final <- proxy_data[-c(1: 395), ]
```


```{r}
#Modify both datasets so they include the same quarters from 1960 - 2015
#results in same dimensions for statistical analysis later
gdp_data_mod_final <- gdp_data_2[-c(1: 51), ]
```

```{r}
#Modify both datasets so they include the same quarters from 1960 - 2015
#results in same dimensions for statistical analysis later
gdp_data_mod_final <- gdp_data_mod_final[-c(225: 257), ]
```

```{r}
#Create geometric mean function to get geometric mean for quarters 
#for proxy_data
geom_mean = function(months){
  result <- c()
  i = 1
  while(i < length(months)) {
    total <- c()
    for (j in 0:2){
      len_total <- length(total)
      total[[len_total + 1]] <- as.numeric(months[i + j])
    }
    value = exp(mean(log(as.numeric(total))))
    len_result <- length(result)
    result[[len_result + 1]] <- value
    i = i + 3
  }
  return (as.numeric(result))
}

```

```{r}
#Create arithmetic mean function to get arithmetic mean for quarters 
#for proxy_data
#Will use this for proxy measures that have negative values
ari_mean = function(months){
  result <- c()
  i = 1
  while(i < length(months)) {
    total <- c()
    for (j in 0:2){
      len_total <- length(total)
      total[[len_total + 1]] <- as.numeric(months[i + j])
    }
    value = mean(as.numeric(total))
    len_result <- length(result)
    result[[len_result + 1]] <- value
    i = i + 3
  }
  return (as.numeric(result))
}

```






```{r}
#Since each measure in the proxy dataset has different missing values/ years with data filled in,
#I will split the large, combined dataset into smaller individual datasets by specific 
#proxy measure


#The 7 measures and their respective datasets:
  
#1. IPOGross (Gross Initial Public Offering), name: combined_data_IPO_Gross
#2. Aggregate ,  name: combined_data_Agreggate_Risk_Aversion
#3. DP (Dividend Price Ratio),  name: combined_data_DPRatio
#4. EPBound (Equity Premium Bound),  name: combined_data_EPBound
#5. SCR (Surplus Consumption Ratio),  name: combined_data_surplus
#6. UNE (Unemployment Rate),  name: combined_data_UNE
#7. PVS (Price of Volatile Stocks),  name: combined_data_PVS
```



```{r}
#Apply geom mean function to different proxy measures by quarter average and
#add them to new, cumulative dataset with that measure for testing
combined_data_IPO_Gross <- data.frame(gdp_data_mod_final)
#Gross IPO By Quarter Added
combined_data_IPO_Gross$IPO_Gross = geom_mean(proxy_data_mod_final$IPO_Gross)
#remove original combined dataset
rm(combined_data)
#
```


```{r}
#Apply geom mean function to different proxy measures by quarter average and
#add them to new, cumulative dataset
#Aggregate Risk Aversion only has data from 1990 - 2010
#Start by changing gdp_data to only include this 
combined_data_Aggregate_Risk_Aversion <- data.frame(gdp_data_mod_final)
combined_data_Aggregate_Risk_Aversion <- combined_data_Aggregate_Risk_Aversion[-c(1: 120), ]
combined_data_Aggregate_Risk_Aversion <- combined_data_Aggregate_Risk_Aversion[-c(85: 104), ]
#Do the same for the proxy data 
proxy_data_cut <- data.frame(proxy_data_mod_final)
proxy_data_cut <- proxy_data_cut[-c(613: 672), ]
proxy_data_cut <- proxy_data_cut[-c(1: 360), ]
#Since aggregate risk aversion has negatives use arithmetic mean for quarter averages
#Aggregate Risk Aversion By Quarter Added
combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion = ari_mean(proxy_data_cut$Agreggate_Risk_Aversion)
#
```


```{r}
#Apply geom mean function to different proxy measures by quarter average and
#add them to new, cumulative dataset with that measure for testing
combined_data_DPRatio <- data.frame(gdp_data_mod_final)
#DPRatio By Quarter Added
combined_data_DPRatio$DPRatio = geom_mean(proxy_data_mod_final$DPRatio)
```

```{r}
#Apply geom mean function to different proxy measures by quarter average and
#add them to new, cumulative dataset
#Equity Premium Bound only has data from 1996 - 2011
#Start by changing gdp_data to only include this 
combined_data_EPBound <- data.frame(gdp_data_mod_final)
combined_data_EPBound <- combined_data_EPBound[-c(1: 144), ]
combined_data_EPBound <- combined_data_EPBound[-c(65: 80), ]
#Do the same for the proxy data 
proxy_data_cut <- data.frame(proxy_data_mod_final)
proxy_data_cut <- proxy_data_cut[-c(625: 672), ]
proxy_data_cut <- proxy_data_cut[-c(1: 432), ]
#Equity Premium Bound By Quarter Added
combined_data_EPBound$EPBound = geom_mean(proxy_data_cut$EP_Bound)
#
```



```{r}
#Apply geom mean function to different proxy measures by quarter average and
#add them to new, cumulative dataset with that measure for testing
combined_data_SCR <- data.frame(gdp_data_mod_final)
#Surplus Consumption Ratio By Quarter Added
#negative values so use arithmetic mean
combined_data_SCR$SCR = ari_mean(proxy_data_mod_final$Surplus_Cons_Ratio)

```

```{r}
#Apply geom mean function to different proxy measures by quarter average and
#add them to new, cumulative dataset with that measure for testing
combined_data_UNE <- data.frame(gdp_data_mod_final)
#Unemployment Rate By Quarter Added
combined_data_UNE$UNE = geom_mean(proxy_data_mod_final$Unemployment_Rate)

```



```{r}
#Apply geom mean function to different proxy measures by quarter average and
#add them to new, cumulative dataset with that measure for testing
#PVS only has data from 1970 quarter 2, and is itself only available by quarter
combined_data_PVS <- data.frame(gdp_data_mod_final)
combined_data_PVS <- combined_data_PVS[-c(1: 41), ]
proxy_data_cut <- data.frame(proxy_data_mod_final)
proxy_data_cut <- proxy_data_cut[-c(1: 123), ]
#Run a for loop to keep every third row with the pvs data of the quarter in 
#the proxy dataset
 i = 3
 total <- c()
 while(i <= length(proxy_data_cut$Price_Volatile_Stocks)) {
    value = proxy_data_cut$Price_Volatile_Stocks[i]
    len_total <- length(total)
    total[[len_total + 1]] <- value
    i = i + 3
  }
#Price of Volatile Stock By Quarter Added
combined_data_PVS$PVS = total

```

```{r}
#All datasets now completed, can begin running tests
```


```{r}

#Equity Premium Proxy Measure 1: Gross IPO, all tests and graphs below


```


```{r}
#Start with an anova test for Gross IPO

#1: Anova test on the quarters to see if there is difference in the Gross IPO 
#by time in the year

IPO.aov <- aov(IPO_Gross ~ Quarter, data = combined_data_IPO_Gross)
# Summary
summary(IPO.aov)


```
```{r}
#P-value of 0.351. Indicates that there are no significant differences in the 
#mean gross ipo by quarter 
```



```{r}
#boxplots of the quarter ~ gross ipo relationship
#Notes: Outliers present for Q3 and Q4
#Notes: Q1 most similar to Q3, Q2 most similar to Q4
#Notes: Potential oscillation between quarters?
boxplot(IPO_Gross~Quarter,data=combined_data_IPO_Gross, main="Gross IPO vs Yearly Quarter",
   xlab="Quarter", ylab="Gross IPO")
```

```{r}
#Run correlation tests between different GDP measures and gross IPO
#Years: 1960 to 2015
#Correlation with GNP
cor(combined_data_IPO_Gross$IPO_Gross, as.numeric(combined_data_IPO_Gross$Gross.national.product))

#Correlation with GDP
cor(combined_data_IPO_Gross$IPO_Gross,  as.numeric(combined_data_IPO_Gross$GDP))

#Correlation with GPDI
cor(combined_data_IPO_Gross$IPO_Gross, as.numeric(combined_data_IPO_Gross$Gross.private.domestic.investment))

#Correlation with nondurable goods
cor(combined_data_IPO_Gross$IPO_Gross, as.numeric(combined_data_IPO_Gross$Nondurable.goods))


#Correlation with personal consumption expenditures
cor(combined_data_IPO_Gross$IPO_Gross, as.numeric(combined_data_IPO_Gross$Personal.consumption.expenditures))

```
```{r}
#all negative correlations around -0.2, indicates weak, negative correlation
```

```{r}
#Linear regression tests
#Start with gross ipo and GNP
lmIPO_GNP = lm(as.numeric(Gross.national.product) ~ IPO_Gross, data = combined_data_IPO_Gross) 
summary(lmIPO_GNP) 

#try with no intercept now
lmIPO_GNP_NOINT = lm(as.numeric(Gross.national.product) ~ IPO_Gross - 1, data = combined_data_IPO_Gross) 
summary(lmIPO_GNP_NOINT) 
```

```{r}
#Linear regression tests
#gross ipo and gdp
lmIPO_GDP = lm(as.numeric(GDP) ~ IPO_Gross, data = combined_data_IPO_Gross) 
summary(lmIPO_GDP) 

#try with no intercept now (X - 1)
lmIPO_GDP_NOINT = lm(as.numeric(GDP) ~ IPO_Gross - 1, data = combined_data_IPO_Gross) 
summary(lmIPO_GDP_NOINT) 
```

```{r}
#Linear regression tests
#gross ipo and Gross private domestic investment
lmIPO_GDP = lm(as.numeric(Gross.private.domestic.investment) ~ IPO_Gross, data = combined_data_IPO_Gross) 
summary(lmIPO_GDP) 

#try with no intercept now (X - 1)
lmIPO_GPDI_NOINT = lm(as.numeric(Gross.private.domestic.investment) ~ IPO_Gross - 1, data = combined_data_IPO_Gross) 
summary(lmIPO_GPDI_NOINT) 
```
```{r}
#Linear regression tests
#gross ipo and nondurable goods
lmIPO_NDG = lm(as.numeric(Nondurable.goods) ~ IPO_Gross, data = combined_data_IPO_Gross) 
summary(lmIPO_NDG) 

#try with no intercept now (X - 1)
lmIPO_NDG_NOINT = lm(as.numeric(Nondurable.goods) ~ IPO_Gross - 1, data = combined_data_IPO_Gross) 
summary(lmIPO_NDG_NOINT) 
```
```{r}
#Linear regression tests
#gross ipo and personal consumption expenditures
lmIPO_PCE = lm(as.numeric(Personal.consumption.expenditures) ~ IPO_Gross, data = combined_data_IPO_Gross) 
summary(lmIPO_PCE) 

#try with no intercept now (X - 1)
lmIPO_PCE_NOINT = lm(as.numeric(Personal.consumption.expenditures) ~ IPO_Gross - 1, data = combined_data_IPO_Gross) 
summary(lmIPO_PCE_NOINT) 
```



```{r}
#Make scatterplots of relationships, color by quarter
#Start with IPO Gross and GNP
 combined_data_IPO_Gross|>
  ggplot(aes(x = IPO_Gross, y = Gross.national.product,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "Gross IPO", y = "GNP", color = "Quarter", 
       title = "Gross IPO vs Gross National Product by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#IPO Gross and GDP
 combined_data_IPO_Gross|>
  ggplot(aes(x = IPO_Gross, y = GDP,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "Gross IPO", y = "GDP", color = "Quarter", 
       title = "Gross IPO vs Gross Domestic Product by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#IPO Gross and GPDI
 combined_data_IPO_Gross|>
  ggplot(aes(x = IPO_Gross, y = Gross.private.domestic.investment,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "Gross IPO", y = "Gross private domestic investment", color = "Quarter", 
       title = "Gross IPO vs Gross private domestic investment by Quarter")
```
```{r}
#Make scatterplots of relationships, color by quarter
#IPO Gross and Nondurable Goods
 combined_data_IPO_Gross|>
  ggplot(aes(x = IPO_Gross, y = Nondurable.goods,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "Gross IPO", y = "Nondurable Goods", color = "Quarter", 
       title = "Gross IPO vs Nondurable Goods by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#IPO Gross and Personal consumption expenditures
 combined_data_IPO_Gross|>
  ggplot(aes(x = IPO_Gross, y = Personal.consumption.expenditures,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "Gross IPO", y = "Personal consumption expenditures", color = "Quarter", 
       title = "Gross IPO vs Personal Consumption Expenditures by Quarter")
```


```{r}

#Equity Premium Proxy Measure 2: Dividend Price ratio, all tests and graphs below


```

```{r}
#Start with an anova test for DP ratio

#1: Anova test on the quarters to see if there is difference in the DP Ratio
#by time in the year

DP.aov <- aov(DPRatio ~ Quarter, data = combined_data_DPRatio)
# Summary
summary(DP.aov)


```
```{r}
#P-value of 0.996. Indicates that there are no significant differences in the 
#mean DP Ratio by quarter 
```



```{r}
#boxplots of the quarter ~ gross ipo relationship
#Notes: No real Outliers 
#Notes: Almost all 4 quarters identical
#Notes: No real oscillation between quarters like with gross IPO
#Notes: Q3 has the smallest IQR
boxplot(DPRatio~Quarter,data=combined_data_DPRatio, main="DP Ratio vs Yearly Quarter",
   xlab="Quarter", ylab="DP Ratio")
```

```{r}
#Run correlation tests between different GDP measures and DPRatio
#Years: 1960 to 2015 (Full Data)
#Correlation with GNP
cor(combined_data_DPRatio$DPRatio, as.numeric(combined_data_DPRatio$Gross.national.product))

#Correlation with GDP
cor(combined_data_DPRatio$DPRatio,  as.numeric(combined_data_DPRatio$GDP))

#Correlation with GPDI
cor(combined_data_DPRatio$DPRatio, as.numeric(combined_data_DPRatio$Gross.private.domestic.investment))

#Correlation with nondurable goods
cor(combined_data_DPRatio$DPRatio, as.numeric(combined_data_DPRatio$Nondurable.goods))


#Correlation with personal consumption expenditures
cor(combined_data_DPRatio$DPRatio, as.numeric(combined_data_DPRatio$Personal.consumption.expenditures))

```
```{r}
#Notes: All positive correlations, greater than 0.6 for GDP, GNP, and Personal consumption expenditures indicating 
#indicating strong correlations with those items
```


```{r}
#Linear regression tests
#Start with DPRatio and GNP
lmDP_GNP = lm(as.numeric(Gross.national.product) ~ DPRatio, data = combined_data_DPRatio) 
summary(lmDP_GNP) 

#try with no intercept now
lmDP_GNP_NOINT = lm(as.numeric(Gross.national.product) ~ DPRatio - 1, data = combined_data_DPRatio) 
summary(lmDP_GNP_NOINT) 
```

```{r}
#Linear regression tests
#DPRatio and gdp
lmDP_GDP = lm(as.numeric(GDP) ~ DPRatio, data = combined_data_DPRatio) 
summary(lmDP_GDP) 

#try with no intercept now (X - 1)
lmDP_GDP_NOINT = lm(as.numeric(GDP) ~ DPRatio - 1, data = combined_data_DPRatio) 
summary(lmDP_GDP_NOINT) 
```

```{r}
#Linear regression tests
#DPRatio and Gross private domestic investment
lmDP_GPDI = lm(as.numeric(Gross.private.domestic.investment) ~ DPRatio, data = combined_data_DPRatio) 
summary(lmDP_GPDI) 

#try with no intercept now (X - 1)
lmDP_GPDI_NOINT = lm(as.numeric(Gross.private.domestic.investment) ~ DPRatio - 1, data = combined_data_DPRatio) 
summary(lmDP_GPDI_NOINT) 
```
```{r}
#Linear regression tests
#DPRatio and nondurable goods
lmDP_NDG = lm(as.numeric(Nondurable.goods) ~ DPRatio, data = combined_data_DPRatio) 
summary(lmDP_NDG) 

#try with no intercept now (X - 1)
lmDP_NDG_NOINT = lm(as.numeric(Nondurable.goods) ~ DPRatio - 1, data = combined_data_DPRatio) 
summary(lmDP_NDG_NOINT) 
```
```{r}
#Linear regression tests
#gross ipo and personal consumption expenditures
lmDP_PCE = lm(as.numeric(Personal.consumption.expenditures) ~ DPRatio, data = combined_data_DPRatio) 
summary(lmDP_PCE) 

#try with no intercept now (X - 1)
lmDP_PCE_NOINT = lm(as.numeric(Personal.consumption.expenditures) ~ DPRatio - 1, data = combined_data_DPRatio) 
summary(lmDP_PCE_NOINT) 
```

```{r}
#Make scatterplots of relationships, color by quarter
#Start with DPRatio and GNP
 combined_data_DPRatio|>
  ggplot(aes(x = DPRatio, y = Gross.national.product,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "DPRatio", y = "GNP", color = "Quarter", 
       title = "DPRatio vs Gross National Product by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#DPRatio and GDP
 combined_data_DPRatio|>
  ggplot(aes(x = DPRatio, y = GDP,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "DPRatio", y = "GDP", color = "Quarter", 
       title = "DPRatio vs Gross Domestic Product by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#IPO Gross and GPDI
 combined_data_DPRatio|>
  ggplot(aes(x = DPRatio, y = Gross.private.domestic.investment,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "DPRatio", y = "Gross private domestic investment", color = "Quarter", 
       title = "DPRatio vs Gross private domestic investment by Quarter")
```
```{r}
#Make scatterplots of relationships, color by quarter
#IPO Gross and Nondurable Goods
 combined_data_DPRatio|>
  ggplot(aes(x = DPRatio, y = Nondurable.goods,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "DPRatio", y = "Nondurable Goods", color = "Quarter", 
       title = "DPRatio vs Nondurable Goods by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#IPO Gross and Personal consumption expenditures
 combined_data_DPRatio|>
  ggplot(aes(x = DPRatio, y = Personal.consumption.expenditures,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "DPRatio", y = "Personal consumption expenditures", color = "Quarter", 
       title = "DPRatio vs Personal Consumption Expenditures by Quarter")
```

```{r}

#Equity Premium Proxy Measure 3: EPBound, all tests and graphs below


```

```{r}
#Start with an anova test for EPBound

#1: Anova test on the quarters to see if there is difference in the Gross IPO 
#by time in the year

EP.aov <- aov(EPBound ~ Quarter, data = combined_data_EPBound)
# Summary
summary(EP.aov)


```
```{r}
#P-value of 0.521. Indicates that there are no significant differences in the 
#mean gross EPBound by quarter 
```



```{r}
#boxplots of the quarter ~ gross ipo relationship
#Notes: Outliers present for all quarters
#Notes: Q1 and Q2 medians similiar, Q1 and Q4 similiar IQR's
#Notes: No distinguishable oscillation between quarters
boxplot( EPBound~Quarter,data=combined_data_EPBound, main="EPBound vs Yearly Quarter",
   xlab="Quarter", ylab=" EPBound")
```

```{r}
#Run correlation tests between different GDP measures and EPBound
#Years: 1960 to 2015
#Correlation with GNP
cor(combined_data_EPBound$EPBound, as.numeric(combined_data_EPBound$Gross.national.product))

#Correlation with GDP
cor(combined_data_EPBound$EPBound,  as.numeric(combined_data_EPBound$GDP))

#Correlation with GPDI
cor(combined_data_EPBound$EPBound, as.numeric(combined_data_EPBound$Gross.private.domestic.investment))

#Correlation with nondurable goods
cor(combined_data_EPBound$EPBound, as.numeric(combined_data_EPBound$Nondurable.goods))


#Correlation with personal consumption expenditures
cor(combined_data_EPBound$EPBound, as.numeric(combined_data_EPBound$Personal.consumption.expenditures))

```
```{r}
#all negative correlations, personal consumption expenditures at -0.71 indicates strong negative relationship 
```


```{r}
#Linear regression tests
#Start with EPBound and GNP
lmEPBound_GNP = lm(as.numeric(Gross.national.product) ~ EPBound, data = combined_data_EPBound) 
summary(lmIPO_GNP) 

#try with no intercept now
lmEPBound_GNP_NOINT = lm(as.numeric(Gross.national.product) ~ EPBound - 1, data = combined_data_EPBound) 
summary(lmIPO_GNP_NOINT) 
```

```{r}
#Linear regression tests
#EPBound and gdp
lmEPBound_GDP = lm(as.numeric(GDP) ~ EPBound, data = combined_data_EPBound) 
summary(lmEPBound_GDP) 

#try with no intercept now (X - 1)
lmEPBound_GDP_NOINT = lm(as.numeric(GDP) ~ EPBound - 1, data = combined_data_EPBound) 
summary(lmEPBound_GDP_NOINT) 
```

```{r}
#Linear regression tests
#EPBound and Gross private domestic investment
lmEPBound_GDP = lm(as.numeric(Gross.private.domestic.investment) ~ EPBound, data = combined_data_EPBound) 
summary(lmEPBound_GDP) 

#try with no intercept now (X - 1)
lmEPBound_GPDI_NOINT = lm(as.numeric(Gross.private.domestic.investment) ~ EPBound - 1, data = combined_data_EPBound) 
summary(lmEPBound_GPDI_NOINT) 
```
```{r}
#Linear regression tests
#EPBound and nondurable goods
lmEPBound_NDG = lm(as.numeric(Nondurable.goods) ~ EPBound, data = combined_data_EPBound) 
summary(lmIPO_NDG) 

#try with no intercept now (X - 1)
lmEPBound_NDG_NOINT = lm(as.numeric(Nondurable.goods) ~ EPBound - 1, data = combined_data_EPBound) 
summary(lmEPBound_NDG_NOINT) 
```
```{r}
#Linear regression tests
#EPBound and personal consumption expenditures
lmEPBound_PCE = lm(as.numeric(Personal.consumption.expenditures) ~ EPBound, data = combined_data_EPBound) 
summary(lmEPBound_PCE) 

#try with no intercept now (X - 1)
lmEPBound_PCE_NOINT = lm(as.numeric(Personal.consumption.expenditures) ~ EPBound - 1, data = combined_data_EPBound) 
summary(lmEPBound_PCE_NOINT) 
```
```{r}
#Make scatterplots of relationships, color by quarter
#Start with IPO Gross and GNP
 combined_data_EPBound|>
  ggplot(aes(x = EPBound, y = Gross.national.product,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "EPBound", y = "GNP", color = "Quarter", 
       title = "EPBound vs Gross National Product by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#IPO Gross and GDP
 combined_data_EPBound|>
  ggplot(aes(x = EPBound, y = GDP,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "EPBound", y = "GDP", color = "Quarter", 
       title = "EPBound vs Gross Domestic Product by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#IPO Gross and GPDI
 combined_data_EPBound|>
  ggplot(aes(x = EPBound, y = Gross.private.domestic.investment,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "EPBound", y = "Gross private domestic investment", color = "Quarter", 
       title = "EPBound vs Gross private domestic investment by Quarter")
```
```{r}
#Make scatterplots of relationships, color by quarter
#IPO Gross and Nondurable Goods
 combined_data_EPBound|>
  ggplot(aes(x = EPBound, y = Nondurable.goods,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "EPBound", y = "Nondurable Goods", color = "Quarter", 
       title = "EPBound vs Nondurable Goods by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#IPO Gross and Personal consumption expenditures
 combined_data_EPBound|>
  ggplot(aes(x = EPBound, y = Personal.consumption.expenditures,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "EPBound", y = "Personal consumption expenditures", color = "Quarter", 
       title = "EPBound vs Personal Consumption Expenditures by Quarter")
```

```{r}

#Risk Aversion Measure 1: PVS, all tests and graphs below


```


```{r}
#Start with an anova test for PVS

#1: Anova test on the quarters to see if there is difference in the Gross IPO 
#by time in the year

PVS.aov <- aov(as.numeric(PVS) ~ Quarter, data = combined_data_PVS)
# Summary
summary(PVS.aov)


```
```{r}
#P-value of 0.288. Indicates that there are no significant differences in the 
#mean gross ipo by quarter 
```



```{r}
#boxplots of the quarter ~ PVS relationship
#Notes: Outliers present for Q1, Q2, and Q4
#Notes: Q4 has the biggest IQR
#Notes: No real oscillation between quarters
boxplot(as.numeric(PVS) ~Quarter,data=combined_data_PVS, main="PVS vs Yearly Quarter",
   xlab="Quarter", ylab="PVS")
```

```{r}
#Run correlation tests between different GDP measures and PVS
#Years: 1960 to 2015
#Correlation with GNP
cor(as.numeric(combined_data_PVS$PVS), as.numeric(combined_data_PVS$Gross.national.product))

#Correlation with GDP
cor(as.numeric(combined_data_PVS$PVS), as.numeric(combined_data_PVS$GDP))

#Correlation with GPDI
cor(as.numeric(combined_data_PVS$PVS), as.numeric(combined_data_PVS$Gross.private.domestic.investment))

#Correlation with nondurable goods
cor(as.numeric(combined_data_PVS$PVS), as.numeric(combined_data_PVS$Nondurable.goods))


#Correlation with personal consumption expenditures
cor(as.numeric(combined_data_PVS$PVS), as.numeric(combined_data_PVS$Personal.consumption.expenditures))

```
```{r}
#all positive correlations below 0.15, indicates weak, positive correlation
```

```{r}
#Linear regression tests
#Start with PVS and GNP
lmPVS_GNP = lm(as.numeric(Gross.national.product) ~ as.numeric(PVS), data = combined_data_PVS) 
summary(lmIPO_GNP) 

#try with no intercept now
lmPVS_GNP_NOINT = lm(as.numeric(Gross.national.product) ~ as.numeric(PVS) - 1, data = combined_data_PVS) 
summary(lmPVS_GNP_NOINT) 
```

```{r}
#Linear regression tests
#gross PVS and gdp
lmPVS_GDP = lm(as.numeric(GDP) ~ as.numeric(PVS), data = combined_data_PVS) 
summary(lmPVS_GDP) 

#try with no intercept now (X - 1)
lmPVS_GDP_NOINT = lm(as.numeric(GDP) ~ as.numeric(PVS) - 1, data = combined_data_PVS) 
summary(lmPVS_GDP_NOINT) 
```

```{r}
#Linear regression tests
#PVS and Gross private domestic investment
lmPVS_GDP = lm(as.numeric(Gross.private.domestic.investment) ~ as.numeric(PVS), data = combined_data_PVS) 
summary(lmPVS_GDP) 

#try with no intercept now (X - 1)
lmPVS_GPDI_NOINT = lm(as.numeric(Gross.private.domestic.investment) ~ as.numeric(PVS) - 1, data = combined_data_PVS) 
summary(lmPVS_GPDI_NOINT) 
```
```{r}
#Linear regression tests
#PVS and nondurable goods
lmPVS_NDG = lm(as.numeric(Nondurable.goods) ~ as.numeric(PVS), data = combined_data_PVS) 
summary(lmPVS_NDG) 

#try with no intercept now (X - 1)
lmPVS_NDG_NOINT = lm(as.numeric(Nondurable.goods) ~ as.numeric(PVS) - 1, data = combined_data_PVS) 
summary(lmPVS_NDG_NOINT) 
```
```{r}
#Linear regression tests
#PVS and personal consumption expenditures
lmPVS_PCE = lm(as.numeric(Personal.consumption.expenditures) ~ as.numeric(PVS), data = combined_data_PVS) 
summary(lmPVS_PCE) 

#try with no intercept now (X - 1)
lmPVS_PCE_NOINT = lm(as.numeric(Personal.consumption.expenditures) ~ as.numeric(PVS) - 1, data = combined_data_PVS) 
summary(lmPVS_PCE_NOINT) 
```
```{r}
#Make scatterplots of relationships, color by quarter
#Start with PVS and GNP
 combined_data_PVS|>
  ggplot(aes(x = as.numeric(PVS), y = Gross.national.product,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "PVS", y = "GNP", color = "Quarter", 
       title = "PVS vs Gross National Product by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#IPO Gross and GDP
 combined_data_PVS|>
  ggplot(aes(x= as.numeric(PVS), y = GDP,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "PVS", y = "GDP", color = "Quarter", 
       title = "PVS vs Gross Domestic Product by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#IPO Gross and GPDI
 combined_data_PVS|>
  ggplot(aes(x = as.numeric(PVS), y = Gross.private.domestic.investment,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "PVS", y = "Gross private domestic investment", color = "Quarter", 
       title = "PVS vs Gross private domestic investment by Quarter")
```
```{r}
#Make scatterplots of relationships, color by quarter
#IPO Gross and Nondurable Goods
 combined_data_PVS|>
  ggplot(aes(x = as.numeric(PVS), y = Nondurable.goods,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "PVS", y = "Nondurable Goods", color = "Quarter", 
       title = "PVS vs Nondurable Goods by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#IPO Gross and Personal consumption expenditures
 combined_data_PVS|>
  ggplot(aes(x = as.numeric(PVS), y = Personal.consumption.expenditures,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "PVS", y = "Personal consumption expenditures", color = "Quarter", 
       title = "PVS vs Personal Consumption Expenditures by Quarter")
```
```{r}

#Risk Aversion Measure 2: Surplus Consumption Ratio, all tests and graphs below


```


```{r}
#Start with an anova test for Surplus Consumption Ratio

#1: Anova test on the quarters to see if there is difference in the Surplus Consumption Ratio
#by time in the year

SCR.aov <- aov(SCR ~ Quarter, data = combined_data_SCR)
# Summary
summary(SCR.aov)


```
```{r}
#P-value of 0.986. Indicates that there are no significant differences in the 
#mean SCR by quarter 
```



```{r}
#boxplots of the quarter ~ gross ipo relationship
#Notes: Outliers present for Q1, Q2 and Q4
#Notes: All quarter IQR's about equal
#Notes: No tengible oscillation between quarters
boxplot(SCR~Quarter,data=combined_data_SCR, main="Surplus Consumption Ratio vs Yearly Quarter",
   xlab="Quarter", ylab="SCR")
```
```{r}
#Run correlation tests between different GDP measures and Surplus Consumption Ratio
#Years: 1960 to 2015 
#Correlation with GNP
cor(combined_data_SCR$SCR, as.numeric(combined_data_SCR$Gross.national.product))

#Correlation with GDP
cor(combined_data_SCR$SCR,  as.numeric(combined_data_SCR$GDP))

#Correlation with GPDI
cor(combined_data_SCR$SCR, as.numeric(combined_data_SCR$Gross.private.domestic.investment))

#Correlation with nondurable goods
cor(combined_data_SCR$SCR, as.numeric(combined_data_SCR$Nondurable.goods))


#Correlation with personal consumption expenditures
cor(combined_data_SCR$SCR, as.numeric(combined_data_SCR$Personal.consumption.expenditures))

```

```{r}
#Purely negative correlations with values strictly less than 0.15 (absolute value) indicating weak, negative associations
```

```{r}
#Linear regression tests
#Start with Surplus Consumption Ratio and GNP
lmSCR_GNP = lm(as.numeric(Gross.national.product) ~ SCR, data = combined_data_SCR) 
summary(lmIPO_GNP) 

#try with no intercept now
lmSCR_GNP_NOINT = lm(as.numeric(Gross.national.product) ~ SCR - 1, data = combined_data_SCR) 
summary(lmSCR_GNP_NOINT) 
```

```{r}
#Linear regression tests
#Surplus Consumption Ratio and gdp
lmSCR_GDP = lm(as.numeric(GDP) ~ SCR, data = combined_data_SCR) 
summary(lmSCR_GDP) 

#try with no intercept now (X - 1)
lmSCR_GDP_NOINT = lm(as.numeric(GDP) ~ SCR - 1, data = combined_data_SCR) 
summary(lmSCR_GDP_NOINT) 
```

```{r}
#Linear regression tests
#Surplus Consumption Ratio and Gross private domestic investment
lmSCR_GDPI = lm(as.numeric(Gross.private.domestic.investment) ~ SCR, data = combined_data_SCR) 
summary(lmSCR_GDPI) 

#try with no intercept now (X - 1)
lmSCR_GDPI_NOINT = lm(as.numeric(Gross.private.domestic.investment) ~ SCR - 1, data = combined_data_SCR) 
summary(lmSCR_GDPI_NOINT) 
```
```{r}
#Linear regression tests
#Surplus Consumption Ratio and nondurable goods
lmSCR_NDG = lm(as.numeric(Nondurable.goods) ~ SCR, data = combined_data_SCR) 
summary(lmSCR_NDG) 

#try with no intercept now (X - 1)
lmSCR_NDG_NOINT = lm(as.numeric(Nondurable.goods) ~ SCR - 1, data = combined_data_SCR) 
summary(lmSCR_NDG_NOINT) 
```
```{r}
#Linear regression tests
#Surplus Consumption Ratio and personal consumption expenditures
lmSCR_PCE = lm(as.numeric(Personal.consumption.expenditures) ~ SCR, data = combined_data_SCR) 
summary(lmSCR_PCE) 

#try with no intercept now (X - 1)
lmSCR_PCE_NOINT = lm(as.numeric(Personal.consumption.expenditures) ~ SCR - 1, data = combined_data_SCR) 
summary(lmSCR_PCE_NOINT) 
```
```{r}
#Make scatterplots of relationships, color by quarter
#Start with SCR and GNP
 combined_data_SCR|>
  ggplot(aes(x = SCR, y = Gross.national.product,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "SCR", y = "GNP", color = "Quarter", 
       title = "SCR vs Gross National Product by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#SCR and GDP
 combined_data_SCR|>
  ggplot(aes(x = SCR, y = GDP,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "SCR", y = "GDP", color = "Quarter", 
       title = "SCR vs Gross Domestic Product by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#SCR and GPDI
 combined_data_SCR|> 
  ggplot(aes(x = SCR, y = Gross.private.domestic.investment,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "SCR", y = "Gross private domestic investment", color = "Quarter", 
       title = "SCR vs Gross private domestic investment by Quarter")
```
```{r}
#Make scatterplots of relationships, color by quarter
#SCR and Nondurable Goods
 combined_data_SCR|>
  ggplot(aes(x = SCR, y = Nondurable.goods,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "SCR", y = "Nondurable Goods", color = "Quarter", 
       title = "SCR vs Nondurable Goods by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#SCR and Personal consumption expenditures
 combined_data_SCR|>
  ggplot(aes(x = SCR, y = Personal.consumption.expenditures,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "SCR", y = "Personal consumption expenditures", color = "Quarter", 
       title = "SCR vs Personal Consumption Expenditures by Quarter")
```


```{r}

#Equity Premium Proxy Measure 3: Aggregate Risk Aversion, all tests and graphs below
rm(combined_data_Agreggate_Risk_Aversion)

```


```{r}
#Start with an anova test for Aggregate Risk Aversion

#1: Anova test on the quarters to see if there is difference in the Aggregate Risk Aversion 
#by time in the year

Aggregate_Risk_Aversion.aov <- aov(Aggregate_Risk_Aversion ~ Quarter, data = combined_data_Aggregate_Risk_Aversion)
# Summary
summary(Aggregate_Risk_Aversion.aov)


```
```{r}
#P-value of 0.963 indicates equal means approximately for risk aversion across quarters
```

```{r}
#Run correlation tests between different GDP measures and Aggregate Risk Aversion
#1990 to 2010
#Correlation with GNP
cor(combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion, as.numeric(combined_data_Aggregate_Risk_Aversion$Gross.national.product))

#Correlation with GDP
cor(combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion,  as.numeric(combined_data_Aggregate_Risk_Aversion$GDP))

#Correlation with GPDI
cor(combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion, as.numeric(combined_data_Aggregate_Risk_Aversion$Gross.private.domestic.investment))

#Correlation with nondurable goods
cor(combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion, as.numeric(combined_data_Aggregate_Risk_Aversion$Nondurable.goods))


#Correlation with personal consumption expenditures
cor(combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion, as.numeric(combined_data_Aggregate_Risk_Aversion$Personal.consumption.expenditures))

```
```{r}
# Mix of positive and negative correlations but all below 0.2 (absolute value) so relatively weak associations
```

```{r}
#Linear regression tests
#Start with Aggregate Risk Aversion and GNP
lmAggregate_Risk_Aversion_GNP = lm(as.numeric(Gross.national.product) ~ Aggregate_Risk_Aversion, data = combined_data_Aggregate_Risk_Aversion) 
summary(lmAggregate_Risk_Aversion_GNP) 

#try with no intercept now
lmAggregate_Risk_Aversion_GNP_NOINT = lm(as.numeric(Gross.national.product) ~ Aggregate_Risk_Aversion - 1, data = combined_data_Aggregate_Risk_Aversion) 
summary(lmAggregate_Risk_Aversion_GNP_NOINT) 
```

```{r}
#Linear regression tests
#Aggregate Risk Aversion and gdp
lmAggregate_Risk_Aversion_GDP = lm(as.numeric(GDP) ~ Aggregate_Risk_Aversion, data = combined_data_Aggregate_Risk_Aversion) 
summary(lmAggregate_Risk_Aversion_GDP) 

#try with no intercept now (X - 1)
lmAggregate_Risk_Aversion_GDP_NOINT = lm(as.numeric(GDP) ~ Aggregate_Risk_Aversion - 1, data = combined_data_Aggregate_Risk_Aversion) 
summary(lmAggregate_Risk_Aversion_GDP_NOINT) 
```

```{r}
#Linear regression tests
#Aggregate Risk Aversion and Gross private domestic investment
lmAggregate_Risk_Aversion_GDP = lm(as.numeric(Gross.private.domestic.investment) ~ Aggregate_Risk_Aversion, data = combined_data_Aggregate_Risk_Aversion) 
summary(lmAggregate_Risk_Aversion_GDP) 

#try with no intercept now (X - 1)
lmAggregate_Risk_Aversion_GPDI_NOINT = lm(as.numeric(Gross.private.domestic.investment) ~ Aggregate_Risk_Aversion - 1, data = combined_data_Aggregate_Risk_Aversion) 
summary(lmAggregate_Risk_Aversion_GPDI_NOINT) 
```
```{r}
#Linear regression tests
#gross ipo and nondurable goods
lmAggregate_Risk_Aversion_NDG = lm(as.numeric(Nondurable.goods) ~ Aggregate_Risk_Aversion, data = combined_data_Aggregate_Risk_Aversion) 
summary(lmAggregate_Risk_Aversion_NDG) 

#try with no intercept now (X - 1)
lmAggregate_Risk_Aversion_NDG_NOINT = lm(as.numeric(Nondurable.goods) ~ Aggregate_Risk_Aversion - 1, data = combined_data_Aggregate_Risk_Aversion) 
summary(lmAggregate_Risk_Aversion_NDG_NOINT) 
```
```{r}
#Linear regression tests
#Aggregate Risk Aversion and personal consumption expenditures
lmAggregate_Risk_Aversion_PCE = lm(as.numeric(Personal.consumption.expenditures) ~ Aggregate_Risk_Aversion, data = combined_data_Aggregate_Risk_Aversion) 
summary(lmAggregate_Risk_Aversion_PCE) 

#try with no intercept now (X - 1)
lmAggregate_Risk_Aversion_PCE_NOINT = lm(as.numeric(Personal.consumption.expenditures) ~ Aggregate_Risk_Aversion - 1, data = combined_data_Aggregate_Risk_Aversion) 
summary(lmAggregate_Risk_Aversion_PCE_NOINT) 
```


```{r}
#Make scatterplots of relationships, color by quarter
#Start with Aggregate Risk Aversion  and GNP
 combined_data_Aggregate_Risk_Aversion|>
  ggplot(aes(x = Aggregate_Risk_Aversion, y = Gross.national.product,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "Aggregate Risk Aversion ", y = "GNP", color = "Quarter", 
       title = "Aggregate Risk Aversion  vs Gross National Product by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#Aggregate Risk Aversion  and GDP
 combined_data_Aggregate_Risk_Aversion|>
  ggplot(aes(x = Aggregate_Risk_Aversion, y = GDP,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "Aggregate Risk Aversion ", y = "GDP", color = "Quarter", 
       title = "Aggregate Risk Aversion  vs Gross Domestic Product by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#Aggregate Risk Aversion  and GPDI
 combined_data_Aggregate_Risk_Aversion|> 
  ggplot(aes(x = Aggregate_Risk_Aversion, y = Gross.private.domestic.investment,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "Aggregate Risk Aversion ", y = "Gross private domestic investment", color = "Quarter", 
       title = "Aggregate Risk Aversion  vs Gross private domestic investment by Quarter")
```
```{r}
#Make scatterplots of relationships, color by quarter
#Aggregate Risk Aversion  and Nondurable Goods
 combined_data_Aggregate_Risk_Aversion|>
  ggplot(aes(x = Aggregate_Risk_Aversion, y = Nondurable.goods,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "Aggregate Risk Aversion ", y = "Nondurable Goods", color = "Quarter", 
       title = "Aggregate Risk Aversion  vs Nondurable Goods by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#Aggregate Risk Aversion  and Personal consumption expenditures
 combined_data_Aggregate_Risk_Aversion|>
  ggplot(aes(x = Aggregate_Risk_Aversion, y = Personal.consumption.expenditures,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "Aggregate Risk Aversion ", y = "Personal consumption expenditures", color = "Quarter", 
       title = "Aggregate Risk Aversion  vs Personal Consumption Expenditures by Quarter")
```


```{r}

#Risk Aversion Measure 4: Unemployment Rate, all tests and graphs below


```


```{r}
#Start with an anova test for Gross IPO

#1: Anova test on the quarters to see if there is difference in the UNE 
#by time in the year

UNE.aov <- aov(UNE  ~ Quarter, data = combined_data_UNE )
# Summary
summary(UNE.aov)


```
```{r}
#P-value of 1. Indicates that there are no significant differences in the 
#mean UNE by quarter 
```



```{r}
#boxplots of the quarter ~ UNE relationship
#Notes: Outliers present for Q1 and Q4
#Notes: No real potential oscillation between quarters
boxplot(UNE ~Quarter,data=combined_data_UNE , main="UNE  vs Yearly Quarter",
   xlab="Quarter", ylab="UNE")
```

```{r}
#Run correlation tests between different GDP measures and UNE 
#Years: 1960 to 2015
#Correlation with GNP
cor(combined_data_UNE$UNE, as.numeric(combined_data_UNE$Gross.national.product))

#Correlation with GDP
cor(combined_data_UNE$UNE, as.numeric(combined_data_UNE$GDP))

#Correlation with GPDI
cor(combined_data_UNE$UNE, as.numeric(combined_data_UNE$Gross.private.domestic.investment))

#Correlation with nondurable goods
cor(combined_data_UNE$UNE, as.numeric(combined_data_UNE$Nondurable.goods))


#Correlation with personal consumption expenditures
cor(combined_data_UNE$UNE, as.numeric(combined_data_UNE$Personal.consumption.expenditures))

```

```{r}
#Mix of positive and negative correlations, although all less than 0.1 (absolute value)

```

```{r}
#Linear regression tests
#Start with UNE and GNP
lmUNE_GNP = lm(as.numeric(Gross.national.product) ~ UNE, data = combined_data_UNE) 
summary(lmUNE_GNP) 

#try with no intercept now
lmUNE_GNP_NOINT = lm(as.numeric(Gross.national.product) ~ UNE - 1, data = combined_data_UNE) 
summary(lmUNE_GNP_NOINT) 
```

```{r}
#Linear regression tests
#UNE and gdp
lmUNE_GDP = lm(as.numeric(GDP) ~ UNE, data = combined_data_UNE) 
summary(lmEPBound_GDP) 

#try with no intercept now (X - 1)
lmUNE_GDP_NOINT = lm(as.numeric(GDP) ~ UNE - 1, data = combined_data_UNE) 
summary(lmUNE_GDP_NOINT) 
```


```{r}
#Linear regression tests 
#UNE and Gross private domestic investment
lmUNE_GDP = lm(as.numeric(Gross.private.domestic.investment) ~ UNE, data = combined_data_UNE) 
summary(lmUNE_GDP) 

#try with no intercept now (X - 1)
lmUNE_GPDI_NOINT = lm(as.numeric(Gross.private.domestic.investment) ~ UNE - 1, data = combined_data_UNE) 
summary(lmUNE_GPDI_NOINT) 
```
```{r}
#Linear regression tests
#UNE and nondurable goods
lmUNE_NDG = lm(as.numeric(Nondurable.goods) ~ UNE, data = combined_data_UNE) 
summary(lmUNE_NDG) 

#try with no intercept now (X - 1)
lmUNE_NDG_NOINT = lm(as.numeric(Nondurable.goods) ~ UNE - 1, data = combined_data_UNE) 
summary(lmUNE_NDG_NOINT) 
```
```{r}
#Linear regression tests
#UNE and personal consumption expenditures
lmUNE_PCE = lm(as.numeric(Personal.consumption.expenditures) ~ UNE, data = combined_data_UNE) 
summary(lmUNE_PCE) 

#try with no intercept now (X - 1)
lmUNE_PCE_NOINT = lm(as.numeric(Personal.consumption.expenditures) ~ UNE - 1, data = combined_data_UNE) 
summary(lmUNE_PCE_NOINT) 
```
```{r}
#Make scatterplots of relationships, color by quarter
#Start with UNE and GNP
 combined_data_UNE|>
  ggplot(aes(x = as.numeric(UNE), y = Gross.national.product,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "UNE", y = "GNP", color = "Quarter", 
       title = "UNE vs Gross National Product by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#IPO Gross and GDP
 combined_data_UNE|>
  ggplot(aes(x= as.numeric(UNE), y = GDP,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "UNE", y = "GDP", color = "Quarter", 
       title = "UNE vs Gross Domestic Product by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#UNE and GPDI
 combined_data_UNE|>
  ggplot(aes(x = as.numeric(UNE), y = Gross.private.domestic.investment,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "UNE", y = "Gross private domestic investment", color = "Quarter", 
       title = "UNE vs Gross private domestic investment by Quarter")
```
```{r}
#Make scatterplots of relationships, color by quarter
#UNE and Nondurable Goods
 combined_data_UNE|>
  ggplot(aes(x = as.numeric(UNE), y = Nondurable.goods,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "UNE", y = "Nondurable Goods", color = "Quarter", 
       title = "UNE vs Nondurable Goods by Quarter")
```

```{r}
#Make scatterplots of relationships, color by quarter
#UNE and Personal consumption expenditures
 combined_data_UNE|>
  ggplot(aes(x = as.numeric(UNE), y = Personal.consumption.expenditures,
             color = Quarter)) +
  geom_point(alpha = 0.5) +
  labs(x = "UNE", y = "Personal consumption expenditures", color = "Quarter", 
       title = "UNE vs Personal Consumption Expenditures by Quarter")
```

```{r}
#check how to get fitted values
lmIPO_GDP$fitted.values

```

```{r}
library(tidyverse)
#importing the new dataset with recession data by month
USREC_data <- read_csv("USREC.csv")
```

```{r}
#Start by changing the recession data to only include 1960 to 2015 
USREC_data_mod <- data.frame(USREC_data)
USREC_data_mod <- USREC_data_mod[-c(1934: 2033), ]
USREC_data_mod <- USREC_data_mod[-c(1: 1261), ]
```


```{r}
#adjust recession data by quarter


#0 is expansionary, 1 is recessionary
#adjust by quarter, Y = recession, N = no recession
quarter_rec = function(months){
  result <- c()
  i = 1
  while(i < length(months)) {
      len_result <- length(result)
      if (months[i] == 0 & months[i + 1] == 0 &  months[i + 2] == 0) {
        result[[len_result + 1]] <- "N"
      }
      else {
          result[[len_result + 1]] <- "Y"
      }
    i = i + 3
  }
  return (result)
}

#store in vector called quarter_recession
quarter_recession = quarter_rec(USREC_data_mod$USREC)

```



```{r}
#add this new column of recession data to the individual datasets
gdp_data_mod_final$recession = quarter_recession
combined_data_DPRatio$recession = quarter_recession
combined_data_IPO_Gross$recession = quarter_recession
combined_data_SCR$recession = quarter_recession
combined_data_UNE$recession = quarter_recession
#adjust to 1990 to 2010 for aggregate risk aversion dataset
quarter_recession_ARE <- c() 
for (i in 1:84){
quarter_recession_ARE[i] = gdp_data_mod_final$recession[i + 120]
}
combined_data_Aggregate_Risk_Aversion$recession = quarter_recession_ARE

#adjust to 1996 to 2011 for Equity Premium Bound dataset
quarter_recession_EP <- c() 
for (i in 1:64){
quarter_recession_EP[i] = gdp_data_mod_final$recession[i + 144]
}
combined_data_EPBound$recession = quarter_recession_EP

#adjust to 1970 to 2015 for Equity Premium Bound dataset
quarter_recession_PVS <- c() 
for (i in 1:183){
quarter_recession_PVS[i] = gdp_data_mod_final$recession[i + 40]
}
combined_data_PVS$recession = quarter_recession_PVS

#all individual datasets now have recession data per quarter
```


```{r}
#Run tests of equal variancefor each dataset measure by recession
```



```{r}
#Equal variance test by recession for gross_ipo  

#check normality first
qqnorm(combined_data_IPO_Gross$IPO_Gross, pch = 1, frame = FALSE)
qqline(combined_data_IPO_Gross$IPO_Gross, col = "blue", lwd = 2)
#shows a mostly normal distribution with heavy tails 
#RunF-test to compare variances
ftest_IPO_Gross <- var.test(IPO_Gross ~ as.character(recession), data = combined_data_IPO_Gross)
ftest_IPO_Gross
#reject
```

```{r}
#Equal variance test by recession for dp_ratio  

#check normality first
qqnorm(combined_data_DPRatio$DPRatio, pch = 1, frame = FALSE)
qqline(combined_data_DPRatio$DPRatio, col = "blue", lwd = 2)
#Approximately normal distribution 
#RunF-test to compare variances
ftest_DPRatio <- var.test(DPRatio ~ as.character(recession), data = combined_data_DPRatio)
ftest_DPRatio
#fail to reject
```

```{r}
#Equal variance test by recession for EPBound  

#check normality first
qqnorm(combined_data_EPBound$EPBound, pch = 1, frame = FALSE)
qqline(combined_data_EPBound$EPBound, col = "blue", lwd = 2)
#shows an approximately, mostly normal distribution 
#Run F-test to compare variances
ftest_EPBound <- var.test(EPBound ~ as.character(recession), data = combined_data_EPBound)
ftest_EPBound
#reject
```


```{r}
#Equal variance test by recession for Aggregate Risk Aversion  

#check normality first
qqnorm(combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion, pch = 1, frame = FALSE)
qqline(combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion, col = "blue", lwd = 2)
#shows an approximately, mostly normal distribution 
#Run F-test to compare variances
ftest_Aggregate_Risk_Aversion <- var.test(Aggregate_Risk_Aversion ~ as.character(recession), data = combined_data_Aggregate_Risk_Aversion)
ftest_Aggregate_Risk_Aversion
#reject
```

```{r}
#Equal variance test by recession for Price of Volatile Stocks

#check normality first
qqnorm(as.numeric(combined_data_PVS$PVS), pch = 1, frame = FALSE)
qqline(as.numeric(combined_data_PVS$PVS), col = "blue", lwd = 2)
#shows an approximately, mostly normal distribution 
#Run F-test to compare variances
ftest_Aggregate_PVS<- var.test(as.numeric(PVS) ~ as.character(recession), data = combined_data_PVS)
ftest_Aggregate_PVS
#reject
```

```{r}
#Equal variance test by recession for Surplus Consumption Ratio  

#check normality first
qqnorm(combined_data_SCR$SCR, pch = 1, frame = FALSE)
qqline(combined_data_SCR$SCR, col = "blue", lwd = 2)
#shows an approximately, mostly normal distribution 
#Run F-test to compare variances
ftest_SCR <- var.test(SCR ~ as.character(recession), data = combined_data_SCR)
ftest_SCR
#reject
```

```{r}
#Equal variance test by recession for Unemployment Rate
#check normality first
qqnorm(combined_data_UNE$UNE, pch = 1, frame = FALSE)
qqline(combined_data_UNE$UNE, col = "blue", lwd = 2)
#shows an approximately, mostly normal distribution 
#Run F-test to compare variances
ftest_UNE <- var.test(UNE ~ as.character(recession), data = combined_data_UNE)
ftest_UNE
#reject
```
```{r}
#run tests for Heteroscedasticity
#Use Breusch-Pagan Test


#Start with Gross Ipo and GDP
IPO_Gross_GDP_lm <- lm(as.numeric(GDP) ~ IPO_Gross, data = combined_data_IPO_Gross)
combined_data_IPO_Gross$GDP_resi <- IPO_Gross_GDP_lm$residuals
IPO_Gross_GDP.func <- lm(GDP_resi^2 ~ IPO_Gross, data = combined_data_IPO_Gross)
summary(IPO_Gross_GDP.func)

#Gross IPO and GNP
IPO_Gross_Gross.national.product_lm <- lm(as.numeric(Gross.national.product) ~ IPO_Gross, data = combined_data_IPO_Gross)
combined_data_IPO_Gross$Gross.national.product_resi <- IPO_Gross_Gross.national.product_lm$residuals
IPO_Gross_Gross.national.product.func <- lm(Gross.national.product_resi^2 ~ IPO_Gross, data = combined_data_IPO_Gross)
summary(IPO_Gross_Gross.national.product.func)

#Gross IPO and Nondurable goods
IPO_Gross_Nondurable.goods_lm <- lm(as.numeric(Nondurable.goods) ~ IPO_Gross, data = combined_data_IPO_Gross)
combined_data_IPO_Gross$Nondurable.goods_resi <- IPO_Gross_Nondurable.goods_lm$residuals
IPO_Gross_Nondurable.goods.func <- lm(Nondurable.goods_resi^2 ~ IPO_Gross, data = combined_data_IPO_Gross)
summary(IPO_Gross_Nondurable.goods.func)


#Gross IPO and Gross private domestic investment
IPO_Gross_Gross.private.domestic.investment_lm <- lm(as.numeric(Gross.private.domestic.investment) ~ IPO_Gross, data = combined_data_IPO_Gross)
combined_data_IPO_Gross$Gross.private.domestic.investment_resi <- IPO_Gross_Gross.private.domestic.investment_lm$residuals
IPO_Gross_Gross.private.domestic.investment.func <- lm(Gross.private.domestic.investment_resi^2 ~ IPO_Gross, data = combined_data_IPO_Gross)
summary(IPO_Gross_Gross.private.domestic.investment.func)


#Gross IPO and Personal consumption expenditure
IPO_Gross_Personal.consumption.expenditures_lm <- lm(
as.numeric(Personal.consumption.expenditures) ~ IPO_Gross, data = combined_data_IPO_Gross)
combined_data_IPO_Gross$Personal.consumption.expenditures_resi <- IPO_Gross_Personal.consumption.expenditures_lm$residuals
IPO_Gross_Personal.consumption.expenditures.func <- lm(
Personal.consumption.expenditures_resi^2 ~ IPO_Gross, data = combined_data_IPO_Gross)
summary(IPO_Gross_Personal.consumption.expenditures.func)

```

```{r}
#Start with DPRatio and GDP
DPRatio_GDP_lm <- lm(as.numeric(GDP) ~ DPRatio, data = combined_data_DPRatio)
combined_data_DPRatio$GDP_resi <- DPRatio_GDP_lm$residuals
DPRatio_GDP.func <- lm(GDP_resi^2 ~ DPRatio, data = combined_data_DPRatio)
summary(DPRatio_GDP.func)

#DPRatio and GNP
DPRatio_Gross.national.product_lm <- lm(as.numeric(Gross.national.product) ~ DPRatio, data = combined_data_DPRatio)
combined_data_DPRatio$Gross.national.product_resi <- DPRatio_Gross.national.product_lm$residuals
DPRatio_Gross.national.product.func <- lm(Gross.national.product_resi^2 ~ DPRatio, data = combined_data_DPRatio)
summary(DPRatio_Gross.national.product.func)

#DPRatio and Nondurable goods
DPRatio_Nondurable.goods_lm <- lm(as.numeric(Nondurable.goods) ~ DPRatio, data = combined_data_DPRatio)
combined_data_DPRatio$Nondurable.goods_resi <- DPRatio_Nondurable.goods_lm$residuals
DPRatio_Nondurable.goods.func <- lm(Nondurable.goods_resi^2 ~ DPRatio, data = combined_data_DPRatio)
summary(DPRatio_Nondurable.goods.func)


#DPRatio and Gross private domestic investment
DPRatio_Gross.private.domestic.investment_lm <- lm(as.numeric(Gross.private.domestic.investment) ~ DPRatio, data = combined_data_DPRatio)
combined_data_DPRatio$Gross.private.domestic.investment_resi <- DPRatio_Gross.private.domestic.investment_lm$residuals
DPRatio_Gross.private.domestic.investment.func <- lm(Gross.private.domestic.investment_resi^2 ~ DPRatio, data = combined_data_DPRatio)
summary(DPRatio_Gross.private.domestic.investment.func)


#DPRatio and Personal consumption expenditure
DPRatio_Personal.consumption.expenditures_lm <- lm(
as.numeric(Personal.consumption.expenditures) ~ DPRatio, data = combined_data_DPRatio)
combined_data_DPRatio$Personal.consumption.expenditures_resi <- DPRatio_Personal.consumption.expenditures_lm$residuals
DPRatio_Personal.consumption.expenditures.func <- lm(
Personal.consumption.expenditures_resi^2 ~ DPRatio, data = combined_data_DPRatio)
summary(DPRatio_Personal.consumption.expenditures.func)

```


```{r}
#Start with EPBound and GDP
EPBound_GDP_lm <- lm(as.numeric(GDP) ~ EPBound, data = combined_data_EPBound)
combined_data_EPBound$GDP_resi <- EPBound_GDP_lm$residuals
EPBound_GDP.func <- lm(GDP_resi^2 ~ EPBound, data = combined_data_EPBound)
summary(EPBound_GDP.func)

#EPBound and GNP
EPBound_Gross.national.product_lm <- lm(as.numeric(Gross.national.product) ~ as.numeric(EPBound), data = combined_data_EPBound)
combined_data_EPBound$Gross.national.product_resi <- EPBound_Gross.national.product_lm$residuals
EPBound_Gross.national.product.func <- lm(Gross.national.product_resi^2 ~ EPBound, data = combined_data_EPBound)
summary(EPBound_Gross.national.product.func)

#EPBound and Nondurable goods
EPBound_Nondurable.goods_lm <- lm(as.numeric(Nondurable.goods) ~ as.numeric(EPBound), data = combined_data_EPBound)
combined_data_EPBound$Nondurable.goods_resi <- EPBound_Nondurable.goods_lm$residuals
EPBound_Nondurable.goods.func <- lm(Nondurable.goods_resi^2 ~ EPBound, data = combined_data_EPBound)
summary(EPBound_Nondurable.goods.func)


#EPBound and Gross private domestic investment
EPBound_Gross.private.domestic.investment_lm <- lm(as.numeric(Gross.private.domestic.investment) ~ as.numeric(EPBound), data = combined_data_EPBound)
combined_data_EPBound$Gross.private.domestic.investment_resi <- EPBound_Gross.private.domestic.investment_lm$residuals
EPBound_Gross.private.domestic.investment.func <- lm(Gross.private.domestic.investment_resi^2 ~ EPBound, data = combined_data_EPBound)
summary(EPBound_Gross.private.domestic.investment.func)


#EPBound and Personal consumption expenditure
EPBound_Personal.consumption.expenditures_lm <- lm(
as.numeric(Personal.consumption.expenditures) ~ as.numeric(EPBound), data = combined_data_EPBound)
combined_data_EPBound$Personal.consumption.expenditures_resi <- EPBound_Personal.consumption.expenditures_lm$residuals
EPBound_Personal.consumption.expenditures.func <- lm(
Personal.consumption.expenditures_resi^2 ~ EPBound, data = combined_data_EPBound)
summary(EPBound_Personal.consumption.expenditures.func)

```


```{r}
#Start with PVS and GDP
PVS_GDP_lm <- lm(GDP ~ as.numeric(PVS), data = combined_data_PVS)
combined_data_PVS$GDP_resi <- PVS_GDP_lm$residuals
PVS_GDP.func <- lm(GDP_resi^2 ~ as.numeric(PVS), data = combined_data_PVS)
summary(PVS_GDP.func)

#PVS and GNP
PVS_Gross.national.product_lm <- lm(Gross.national.product ~ as.numeric(PVS), data = combined_data_PVS)
combined_data_PVS$Gross.national.product_resi <- PVS_Gross.national.product_lm$residuals
PVS_Gross.national.product.func <- lm(Gross.national.product_resi^2 ~ as.numeric(PVS), data = combined_data_PVS)
summary(PVS_Gross.national.product.func)

#PVS and Nondurable goods
PVS_Nondurable.goods_lm <- lm(Nondurable.goods ~ as.numeric(PVS), data = combined_data_PVS)
combined_data_PVS$Nondurable.goods_resi <- PVS_Nondurable.goods_lm$residuals
PVS_Nondurable.goods.func <- lm(Nondurable.goods_resi^2 ~ as.numeric(PVS), data = combined_data_PVS)
summary(PVS_Nondurable.goods.func)


#EPBound and Gross private domestic investment
PVS_Gross.private.domestic.investment_lm <- lm(Gross.private.domestic.investment ~ as.numeric(PVS), data = combined_data_PVS)
combined_data_PVS$Gross.private.domestic.investment_resi <- PVS_Gross.private.domestic.investment_lm$residuals
PVS_Gross.private.domestic.investment.func <- lm(Gross.private.domestic.investment_resi^2 ~ as.numeric(PVS), data = combined_data_PVS)
summary(PVS_Gross.private.domestic.investment.func)


#EPBound and Personal consumption expenditure
PVS_Personal.consumption.expenditures_lm <- lm(
Personal.consumption.expenditures ~ as.numeric(PVS), data = combined_data_PVS)
combined_data_PVS$Personal.consumption.expenditures_resi <- PVS_Personal.consumption.expenditures_lm$residuals
PVS_Personal.consumption.expenditures.func <- lm(
Personal.consumption.expenditures_resi^2 ~ as.numeric(PVS), data = combined_data_PVS)
summary(PVS_Personal.consumption.expenditures.func)

```

```{r}
#Start with SCR and GDP
SCR_GDP_lm <- lm(GDP ~ as.numeric(SCR), data = combined_data_SCR)
combined_data_SCR$GDP_resi <- SCR_GDP_lm$residuals
SCR_GDP.func <- lm(GDP_resi^2 ~ as.numeric(SCR), data = combined_data_SCR)
summary(SCR_GDP.func)

#SCR and GNP
SCR_Gross.national.product_lm <- lm(Gross.national.product ~ as.numeric(SCR), data = combined_data_SCR)
combined_data_SCR$Gross.national.product_resi <- SCR_Gross.national.product_lm$residuals
SCR_Gross.national.product.func <- lm(Gross.national.product_resi^2 ~ as.numeric(SCR), data = combined_data_SCR)
summary(SCR_Gross.national.product.func)

#SCR and Nondurable goods
SCR_Nondurable.goods_lm <- lm(Nondurable.goods ~ as.numeric(SCR), data = combined_data_SCR)
combined_data_SCR$Nondurable.goods_resi <- SCR_Nondurable.goods_lm$residuals
SCR_Nondurable.goods.func <- lm(Nondurable.goods_resi^2 ~ as.numeric(SCR), data = combined_data_SCR)
summary(SCR_Nondurable.goods.func)


#SCR and Gross private domestic investment
SCR_Gross.private.domestic.investment_lm <- lm(Gross.private.domestic.investment ~ as.numeric(SCR), data = combined_data_SCR)
combined_data_SCR$Gross.private.domestic.investment_resi <- SCR_Gross.private.domestic.investment_lm$residuals
SCR_Gross.private.domestic.investment.func <- lm(Gross.private.domestic.investment_resi^2 ~ as.numeric(SCR), data = combined_data_SCR)
summary(SCR_Gross.private.domestic.investment.func)


#SCR and Personal consumption expenditure
SCR_Personal.consumption.expenditures_lm <- lm(
Personal.consumption.expenditures ~ as.numeric(SCR), data = combined_data_SCR)
combined_data_SCR$Personal.consumption.expenditures_resi <- SCR_Personal.consumption.expenditures_lm$residuals
SCR_Personal.consumption.expenditures.func <- lm(
Personal.consumption.expenditures_resi^2 ~ as.numeric(SCR), data = combined_data_SCR)
summary(SCR_Personal.consumption.expenditures.func)

```

```{r}
#Start with Aggregate Risk Aversion and GDP
Aggregate_Risk_Aversion_GDP_lm <- lm(GDP ~ Aggregate_Risk_Aversion, data = combined_data_Aggregate_Risk_Aversion)
combined_data_Aggregate_Risk_Aversion$GDP_resi <- Aggregate_Risk_Aversion_GDP_lm$residuals
Aggregate_Risk_Aversion_GDP.func <- lm(GDP_resi^2 ~ Aggregate_Risk_Aversion, data = combined_data_Aggregate_Risk_Aversion)
summary(Aggregate_Risk_Aversion_GDP.func)

#Aggregate Risk Aversion and GNP
Aggregate_Risk_Aversion_Gross.national.product_lm <- lm(Gross.national.product ~ 
Aggregate_Risk_Aversion, data = combined_data_Aggregate_Risk_Aversion)
combined_data_Aggregate_Risk_Aversion$Gross.national.product_resi <- Aggregate_Risk_Aversion_Gross.national.product_lm$residuals
Aggregate_Risk_Aversion_Gross.national.product.func <- lm(Gross.national.product_resi^2 ~ Aggregate_Risk_Aversion, data = combined_data_Aggregate_Risk_Aversion)
summary(Aggregate_Risk_Aversion_Gross.national.product.func)

#Aggregate Risk Aversion and Nondurable goods
Aggregate_Risk_Aversion_Nondurable.goods_lm <- lm(Nondurable.goods ~ Aggregate_Risk_Aversion, data = combined_data_Aggregate_Risk_Aversion)
combined_data_Aggregate_Risk_Aversion$Nondurable.goods_resi <- Aggregate_Risk_Aversion_Nondurable.goods_lm$residuals
Aggregate_Risk_Aversion_Nondurable.goods.func <- lm(Nondurable.goods_resi^2 ~ Aggregate_Risk_Aversion, data = combined_data_Aggregate_Risk_Aversion)
summary(Aggregate_Risk_Aversion_Nondurable.goods.func)


#Aggregate Risk Aversion and Gross private domestic investment
Aggregate_Risk_Aversion_Gross.private.domestic.investment_lm <- lm(Gross.private.domestic.investment ~ Aggregate_Risk_Aversion, data = combined_data_Aggregate_Risk_Aversion)
combined_data_Aggregate_Risk_Aversion$Gross.private.domestic.investment_resi <- Aggregate_Risk_Aversion_Gross.private.domestic.investment_lm$residuals
Aggregate_Risk_Aversion_Gross.private.domestic.investment.func <- lm(Gross.private.domestic.investment_resi^2 ~ Aggregate_Risk_Aversion, data = combined_data_Aggregate_Risk_Aversion)
summary(Aggregate_Risk_Aversion_Gross.private.domestic.investment.func)


#Aggregate Risk Aversion and Personal consumption expenditure
Aggregate_Risk_Aversion_Personal.consumption.expenditures_lm <- lm(
Personal.consumption.expenditures ~ Aggregate_Risk_Aversion, data = combined_data_Aggregate_Risk_Aversion)
combined_data_Aggregate_Risk_Aversion$Personal.consumption.expenditures_resi <- Aggregate_Risk_Aversion_Personal.consumption.expenditures_lm$residuals
Aggregate_Risk_Aversion_Personal.consumption.expenditures.func <- lm(
Personal.consumption.expenditures_resi^2 ~ Aggregate_Risk_Aversion, data = combined_data_Aggregate_Risk_Aversion)
summary(Aggregate_Risk_Aversion_Personal.consumption.expenditures.func)

```
```{r}
#Start with UNE and GDP
UNE_GDP_lm <- lm(GDP ~ UNE, data = combined_data_UNE)
combined_data_UNE$GDP_resi <- UNE_GDP_lm$residuals
UNE_GDP.func <- lm(GDP_resi^2 ~ UNE, data = combined_data_UNE)
summary(UNE_GDP.func)

#UNE and GNP
UNE_Gross.national.product_lm <- lm(Gross.national.product ~ UNE, data = combined_data_UNE)
combined_data_UNE$Gross.national.product_resi <- UNE_Gross.national.product_lm$residuals
UNE_Gross.national.product.func <- lm(Gross.national.product_resi^2 ~ UNE, data = combined_data_UNE)
summary(UNE_Gross.national.product.func)

#UNE and Nondurable goods
UNE_Nondurable.goods_lm <- lm(Nondurable.goods ~ UNE, data = combined_data_UNE)
combined_data_UNE$Nondurable.goods_resi <- UNE_Nondurable.goods_lm$residuals
UNE_Nondurable.goods.func <- lm(Nondurable.goods_resi^2 ~ UNE, data = combined_data_UNE)
summary(UNE_Nondurable.goods.func)


#UNE and Gross private domestic investment
UNE_Gross.private.domestic.investment_lm <- lm(Gross.private.domestic.investment ~ UNE, data = combined_data_UNE)
combined_data_UNE$Gross.private.domestic.investment_resi <- UNE_Gross.private.domestic.investment_lm$residuals
UNE_Gross.private.domestic.investment.func <- lm(Gross.private.domestic.investment_resi^2 ~ UNE, data = combined_data_UNE)
summary(UNE_Gross.private.domestic.investment.func)


#UNE and Personal consumption expenditure
UNE_Personal.consumption.expenditures_lm <- lm(
Personal.consumption.expenditures ~ UNE, data = combined_data_UNE)
combined_data_UNE$Personal.consumption.expenditures_resi <- UNE_Personal.consumption.expenditures_lm$residuals
UNE_Personal.consumption.expenditures.func <- lm(
Personal.consumption.expenditures_resi^2 ~ UNE, data = combined_data_UNE)
summary(UNE_Personal.consumption.expenditures.func)

```






```{r}
combined_data_IPO_Gross$Year = as.integer(unlist(combined_data_IPO_Gross$Year))
IPO_Gross_Year <- as.data.frame(table(unlist(combined_data_IPO_Gross$Year)))
#line plot of gross_ipo by recession over time
#ggplot(data=combined_data_IPO_Gross, aes(x= Goods.2, y= IPO_Gross, group= recession)) +
  #geom_line(linetype="dashed", color="red", size=1.4)+
  #geom_point(color="green", size=5)
```


```{r}
#create function for growth rates for different output measures 
growth_rate = function(months){
  total <- c()
  total[1] = 0
  i = 1
  while(i < length(months)) {
      len_total <- length(total)
      #calculate growth rate
      if (months[i] == 0) {
        #??? what to do
        #for now just set to 0
        total[[len_total + 1]] = 0
      }
      
      else {
        total[[len_total + 1]] <- (months[i + 1] - months[i]) / months[i]
      }
    i = i + 1
  }
  return (as.numeric(total))
}
```


```{r}
#run growth rate function on gdp measures in each dataset
#Start with IPO Gross
combined_data_IPO_Gross$GDP_growth = growth_rate(as.numeric(combined_data_IPO_Gross$GDP))
combined_data_IPO_Gross$Personal.consumption.expenditures_growth = growth_rate(as.numeric(combined_data_IPO_Gross$Personal.consumption.expenditures))
combined_data_IPO_Gross$Gross.national.product_growth = growth_rate(as.numeric(combined_data_IPO_Gross$Gross.national.product))
combined_data_IPO_Gross$Nondurable.goods_growth = growth_rate(as.numeric(combined_data_IPO_Gross$Nondurable.goods))
combined_data_IPO_Gross$Gross.private.domestic.investment_growth = growth_rate(as.numeric(combined_data_IPO_Gross$Gross.private.domestic.investment))

#DPRatio Growth Adjustments
combined_data_DPRatio$GDP_growth = growth_rate(as.numeric(combined_data_DPRatio$GDP))
combined_data_DPRatio$Personal.consumption.expenditures_growth = growth_rate(as.numeric(combined_data_DPRatio$Personal.consumption.expenditures))
combined_data_DPRatio$Gross.national.product_growth = growth_rate(as.numeric(combined_data_DPRatio$Gross.national.product))
combined_data_DPRatio$Nondurable.goods_growth = growth_rate(as.numeric(combined_data_DPRatio$Nondurable.goods))
combined_data_DPRatio$Gross.private.domestic.investment_growth = growth_rate(as.numeric(combined_data_DPRatio$Gross.private.domestic.investment))


#EPBound Growth Adjustments
combined_data_EPBound$GDP_growth = growth_rate(as.numeric(combined_data_EPBound$GDP))
combined_data_EPBound$Personal.consumption.expenditures_growth = growth_rate(as.numeric(combined_data_EPBound$Personal.consumption.expenditures))
combined_data_EPBound$Gross.national.product_growth = growth_rate(as.numeric(combined_data_EPBound$Gross.national.product))
combined_data_EPBound$Nondurable.goods_growth = growth_rate(as.numeric(combined_data_EPBound$Nondurable.goods))
combined_data_EPBound$Gross.private.domestic.investment_growth = growth_rate(as.numeric(combined_data_EPBound$Gross.private.domestic.investment))


#Price of Volatile Stocks Growth Adjustments
combined_data_PVS$GDP_growth = growth_rate(as.numeric(combined_data_PVS$GDP))
combined_data_PVS$Personal.consumption.expenditures_growth = growth_rate(as.numeric(combined_data_PVS$Personal.consumption.expenditures))
combined_data_PVS$Gross.national.product_growth = growth_rate(as.numeric(combined_data_PVS$Gross.national.product))
combined_data_PVS$Nondurable.goods_growth = growth_rate(as.numeric(combined_data_PVS$Nondurable.goods))
combined_data_PVS$Gross.private.domestic.investment_growth = growth_rate(as.numeric(combined_data_PVS$Gross.private.domestic.investment))

#Surplus Consumption Ratio Growth Adjustments
combined_data_SCR$GDP_growth = growth_rate(as.numeric(combined_data_SCR$GDP))
combined_data_SCR$Personal.consumption.expenditures_growth = growth_rate(as.numeric(combined_data_SCR$Personal.consumption.expenditures))
combined_data_SCR$Gross.national.product_growth = growth_rate(as.numeric(combined_data_SCR$Gross.national.product))
combined_data_SCR$Nondurable.goods_growth = growth_rate(as.numeric(combined_data_SCR$Nondurable.goods))
combined_data_SCR$Gross.private.domestic.investment_growth = growth_rate(as.numeric(combined_data_SCR$Gross.private.domestic.investment))

#Aggregate Risk Aversion Growth Adjustments
combined_data_Aggregate_Risk_Aversion$GDP_growth = growth_rate(as.numeric(combined_data_Aggregate_Risk_Aversion$GDP))
combined_data_Aggregate_Risk_Aversion$Personal.consumption.expenditures_growth = growth_rate(as.numeric(combined_data_Aggregate_Risk_Aversion$Personal.consumption.expenditures))
combined_data_Aggregate_Risk_Aversion$Gross.national.product_growth = growth_rate(as.numeric(combined_data_Aggregate_Risk_Aversion$Gross.national.product))
combined_data_Aggregate_Risk_Aversion$Nondurable.goods_growth = growth_rate(as.numeric(combined_data_Aggregate_Risk_Aversion$Nondurable.goods))
combined_data_Aggregate_Risk_Aversion$Gross.private.domestic.investment_growth = growth_rate(as.numeric(combined_data_Aggregate_Risk_Aversion$Gross.private.domestic.investment))

#Unemployment Rate Growth Adjustments 
combined_data_UNE$GDP_growth = growth_rate(as.numeric(combined_data_UNE$GDP))
combined_data_UNE$Personal.consumption.expenditures_growth = growth_rate(as.numeric(combined_data_UNE$Personal.consumption.expenditures))
combined_data_UNE$Gross.national.product_growth = growth_rate(as.numeric(combined_data_UNE$Gross.national.product))
combined_data_UNE$Nondurable.goods_growth = growth_rate(as.numeric(combined_data_UNE$Nondurable.goods))
combined_data_UNE$Gross.private.domestic.investment_growth = growth_rate(as.numeric(combined_data_UNE$Gross.private.domestic.investment))

```



```{r}
#install.packages("lmtest")


```
```{r}
library(lmtest)

#IPO_Gross
bptest(IPO_Gross_GDP_lm)
bptest(IPO_Gross_Gross.national.product_lm)
bptest(IPO_Gross_Nondurable.goods_lm)
bptest(IPO_Gross_Gross.private.domestic.investment_lm)
bptest(IPO_Gross_Personal.consumption.expenditures_lm)

#DPRatio
bptest(DPRatio_GDP_lm)
bptest(DPRatio_Gross.national.product_lm)
bptest(DPRatio_Nondurable.goods_lm)
bptest(DPRatio_Gross.private.domestic.investment_lm)
bptest(DPRatio_Personal.consumption.expenditures_lm)


#EPBound
bptest(EPBound_GDP_lm)
bptest(EPBound_Gross.national.product_lm)
bptest(EPBound_Nondurable.goods_lm)
bptest(EPBound_Gross.private.domestic.investment_lm)
bptest(EPBound_Personal.consumption.expenditures_lm)



#Gives same results as initial Breusch-Pagan Test code above
#so we can stop here
```



```{r}
#Time series graphs
#Look at graphs of these growth rates versus the various equity premium/risk aversion measures
#install.packages("TSstudio")
```
```{r}
#library("TSstudio")
```


[**3 Equity Premium measure graphs against various GDP measures, ALL YEARS **]

```{r}
x = combined_data_IPO_Gross$Year
y1 = combined_data_IPO_Gross$IPO_Gross
y2 = combined_data_IPO_Gross$GDP
y3 = combined_data_IPO_Gross$Gross.national.product
y4 = combined_data_IPO_Gross$Gross.private.domestic.investment
y5 = combined_data_IPO_Gross$Nondurable.goods
y6 = combined_data_IPO_Gross$Personal.consumption.expenditures

plot(x, y1, type="b", pch=16, col="red", main="Gross IPO vs various GDP Measures, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Gross IPO vs. various GDP measures")
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
lines(x, y3, pch=18, col="green", type="b", lty=2)
lines(x, y4, pch=18, col="black", type="b", lty=2)
lines(x, y5, pch=18, col="yellow", type="b", lty=2)
lines(x, y6, pch=18, col="orange", type="b", lty=2)
legend(2005, 90, legend=c("IPO Gross", "GDP", "GNP", "GPDI", "NG", "PCE" ),
       col=c("red", "blue", "green", "black", "yellow","orange"), lty=1:2, cex=0.8)



```




```{r}
#EP Bound 
#Y-axis values are too different so split into 2
x = combined_data_EPBound$Year
y1 = combined_data_EPBound$EPBound

plot(x, y1, type="b", pch=16, col="red", main="EPBound Over Time, 1996 - 2011", sub="1996-2011",
  xlab="Year", ylab="EPBound")
```


```{r}
x = combined_data_EPBound$Year
y2 = combined_data_EPBound$GDP
y3 = combined_data_EPBound$Gross.national.product
y4 = combined_data_EPBound$Gross.private.domestic.investment
y5 = combined_data_EPBound$Nondurable.goods
y6 = combined_data_EPBound$Personal.consumption.expenditures

plot(x, y2, type="b", pch=16, col="red", main="Various GDP Measures over time, 1996 - 2011", sub="1996-2011",
  xlab="Year", ylab="Various GDP measures", xlim=c(1996, 2011))
# Add lines for gdp measures
lines(x, y3, pch=18, col="green", type="b", lty=2)
lines(x, y4, pch=18, col="black", type="b", lty=2)
lines(x, y5, pch=18, col="yellow", type="b", lty=2)
lines(x, y6, pch=18, col="orange", type="b", lty=2)
legend(2005, 90, legend=c("GDP", "GNP", "GPDI", "NG", "PCE" ),
       col=c("red", "blue", "green", "black", "yellow"), lty=1:2, cex=0.8)
```


```{r}
#DP ratio
#Y-axis values are too different so split into 2
x = combined_data_DPRatio$Year
y1 = combined_data_DPRatio$DPRatio

plot(x, y1, type="b", pch=16, col="red", main="DPRatio Over Time, 1960 - 2015", sub="1960-2011",
  xlab="Year", ylab="DPRatio")

```


```{r}
x = combined_data_DPRatio$Year
y2 = combined_data_DPRatio$GDP
y3 = combined_data_DPRatio$Gross.national.product
y4 = combined_data_DPRatio$Gross.private.domestic.investment
y5 = combined_data_DPRatio$Nondurable.goods
y6 = combined_data_DPRatio$Personal.consumption.expenditures

plot(x, y2, type="b", pch=16, col="red", main="Various GDP Measures over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Various GDP measures", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y3, pch=18, col="green", type="b", lty=2)
lines(x, y4, pch=18, col="black", type="b", lty=2)
lines(x, y5, pch=18, col="yellow", type="b", lty=2)
lines(x, y6, pch=18, col="orange", type="b", lty=2)
legend(2005, 90, legend=c("GDP", "GNP", "GPDI", "NG", "PCE" ),
       col=c("red", "blue", "green", "black", "yellow"), lty=1:2, cex=0.8)
```







[**Gross IPO over time vs various GDP Measure Growth Rates**]
```{r}
#Gross IPO vs GDP growth over time 
x = combined_data_IPO_Gross$Year
y1 = combined_data_IPO_Gross$IPO_Gross
y2 = combined_data_IPO_Gross$GDP_growth
plot(x, y1, type="b", pch=16, col="red", main="Gross IPO vs GDP growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Gross IPO vs GDP", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("Gross IPO", "GDP growth"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```

```{r}
#Gross IPO vs NDG growth over time 
x = combined_data_IPO_Gross$Year
y1 = combined_data_IPO_Gross$IPO_Gross
y2 = combined_data_IPO_Gross$Nondurable.goods_growth
plot(x, y1, type="b", pch=16, col="red", main="Gross IPO vs NDG growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Gross IPO vs NDG", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("Gross IPO", "NDG growth"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```

```{r}
#Gross IPO vs PCE growth over time 
x = combined_data_IPO_Gross$Year
y1 = combined_data_IPO_Gross$IPO_Gross
y2 = combined_data_IPO_Gross$Personal.consumption.expenditures_growth
plot(x, y1, type="b", pch=16, col="red", main="Gross IPO vs PCE growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Gross IPO vs PCE", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("Gross IPO", "PCE growth"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```


```{r}
#Gross IPO vs GPDI growth over time 
x = combined_data_IPO_Gross$Year
y1 = combined_data_IPO_Gross$IPO_Gross
y2 = combined_data_IPO_Gross$Gross.private.domestic.investment_growth
plot(x, y1, type="b", pch=16, col="red", main="Gross IPO vs GPDI growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Gross IPO vs GPDI", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("Gross IPO", "GPDI growth"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```


```{r}
#Gross IPO vs GNP growth over time 
x = combined_data_IPO_Gross$Year
y1 = combined_data_IPO_Gross$IPO_Gross
y2 = combined_data_IPO_Gross$Gross.national.product_growth
plot(x, y1, type="b", pch=16, col="red", main="Gross IPO vs GNP growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Gross IPO vs GNP", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("Gross IPO", "GNP growth"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```




[**Gross IPO over time vs various GDP Measures**]

```{r}
#Gross IPO vs GDP over time 
x = combined_data_IPO_Gross$Year
y1 = combined_data_IPO_Gross$IPO_Gross
y2 = combined_data_IPO_Gross$GDP
plot(x, y1, type="b", pch=16, col="red", main="Gross IPO vs GDP over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Gross IPO vs GDP", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("Gross IPO", "GDP"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```

```{r}
#Gross IPO vs NDG over time 
x = combined_data_IPO_Gross$Year
y1 = combined_data_IPO_Gross$IPO_Gross
y2 = combined_data_IPO_Gross$Nondurable.goods
plot(x, y1, type="b", pch=16, col="red", main="Gross IPO vs NDG over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Gross IPO vs NDGs", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("Gross IPO", "NDG"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```

```{r}
#Gross IPO vs PCE over time 
x = combined_data_IPO_Gross$Year
y1 = combined_data_IPO_Gross$IPO_Gross
y2 = combined_data_IPO_Gross$Personal.consumption.expenditures
plot(x, y1, type="b", pch=16, col="red", main="Gross IPO vs PCE over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Gross IPO vs PCE", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("Gross IPO", "PCE"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```


```{r}
#Gross IPO vs GPDI over time 
x = combined_data_IPO_Gross$Year
y1 = combined_data_IPO_Gross$IPO_Gross
y2 = combined_data_IPO_Gross$Gross.private.domestic.investment
plot(x, y1, type="b", pch=16, col="red", main="Gross IPO vs PCE over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Gross IPO vs PCE", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("Gross IPO", "GPDI"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```


```{r}
#Gross IPO vs GNP over time
x = combined_data_IPO_Gross$Year
y1 = combined_data_IPO_Gross$IPO_Gross
y2 = combined_data_IPO_Gross$Gross.national.product
plot(x, y1, type="b", pch=16, col="red", main="Gross IPO vs GNP over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Gross IPO vs GNP", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("Gross IPO", "GNP"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```








[**EPBound vs various gdp measures**]


```{r}
#EPBound vs GDP growth over time 
x = combined_data_EPBound$Year
y1 = combined_data_EPBound$EPBound
y2 = combined_data_EPBound$GDP_growth
plot(x, y1, type="b", pch=16, col="red", main="EPBound vs GDP growth over time, 1996 - 2011", sub="1996-2011",
  xlab="Year", ylab="EPBound vs GDP", xlim=c(1996, 2011))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("EPBound", "GDP growth"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```

```{r}
#EPBound vs NDG growth over time 
x = combined_data_EPBound$Year
y1 = combined_data_EPBound$EPBound
y2 = combined_data_EPBound$Nondurable.goods_growth
plot(x, y1, type="b", pch=16, col="red", main="EPBound vs NDG growth over time, 1996 - 2011", sub="1996-2011",
  xlab="Year", ylab="EPBound vs NDG", xlim=c(1996, 2011))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("EPBound", "NDG growth"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```

```{r}
#EPBound vs PCE growth over time 
x = combined_data_EPBound$Year
y1 = combined_data_EPBound$EPBound
y2 = combined_data_EPBound$Personal.consumption.expenditures_growth
plot(x, y1, type="b", pch=16, col="red", main="EPBound vs PCE growth over time, 1996 - 2011", sub="1996-2011",
  xlab="Year", ylab="EPBound vs PCE", xlim=c(1996, 2011))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("EPBound", "PCE growth"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```


```{r}
#EPBound vs GPDI growth over time 
x = combined_data_EPBound$Year
y1 = combined_data_EPBound$EPBound
y2 = combined_data_EPBound$Gross.private.domestic.investment_growth
plot(x, y1, type="b", pch=16, col="red", main="EPBound vs GPDI growth over time, 1996 - 2011", sub="1996-2011",
  xlab="Year", ylab="EPBound vs GPDI", xlim=c(1996, 2011))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("EPBound", "GPDI growth"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```


```{r}
#EPBound vs GNP growth over time 
x = combined_data_EPBound$Year
y1 = combined_data_EPBound$EPBound
y2 = combined_data_EPBound$Gross.national.product_growth
plot(x, y1, type="b", pch=16, col="red", main="EPBound vs GNP  growth over time, 1996 - 2011", sub="1960-2015",
  xlab="Year", ylab="EPBound vs GNP", xlim=c(1996, 2011), ylim=c(0, 2.5))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("EPBound", "GNP growth"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```





```{r}
#EPBound vs GDP over time 
x = combined_data_EPBound$Year
y1 = combined_data_EPBound$EPBound
y2 = combined_data_EPBound$GDP
plot(x, y1, type="b", pch=16, col="red", main="EPBound vs GDP over time, 1996 - 2011", sub="1996-2011",
  xlab="Year", ylab="EPBound vs GDPs", xlim=c(1996, 2011))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("EPBound", "GDP"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```

```{r}
#EPBound vs NDG over time 
x = combined_data_EPBound$Year
y1 = combined_data_EPBound$EPBound
y2 = combined_data_EPBound$Nondurable.goods
plot(x, y1, type="b", pch=16, col="red", main="EPBound vs NDG over time, 1996 - 2011", sub="1996-2011",
  xlab="Year", ylab="EPBound vs NDG", xlim=c(1996, 2011))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("EPBound", "NDG"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```

```{r}
#EPBound vs PCE over time 
x = combined_data_EPBound$Year
y1 = combined_data_EPBound$EPBound
y2 = combined_data_EPBound$Personal.consumption.expenditures
plot(x, y1, type="b", pch=16, col="red", main="EPBound vs PCE over time, 1996 - 2011", sub="1996-2011",
  xlab="Year", ylab="EPBound vs PCE", xlim=c(1996, 2011))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("EPBound", "PCE"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```


```{r}
#EPBound vs GPDI over time 
x = combined_data_EPBound$Year
y1 = combined_data_EPBound$EPBound
y2 = combined_data_EPBound$Gross.private.domestic.investment
plot(x, y1, type="b", pch=16, col="red", main="EPBound vs GPDI over time, 1996 - 2011", sub="1996-2011",
  xlab="Year", ylab="EPBound vs GPDI", xlim=c(1996, 2011))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("EPBound", "GPDI"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```


```{r}
#EPBound vs GNP over time 
x = combined_data_EPBound$Year
y1 = combined_data_EPBound$EPBound
y2 = combined_data_EPBound$Gross.national.product_growth
plot(x, y1, type="b", pch=16, col="red", main="EPBound vs GNP over time, 1996 - 2011", sub="1996-2011",
  xlab="Year", ylab="EPBound vs GNP", xlim=c(1996, 2011))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("EPBound", "GNP"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```






[**DPRatio over time vs various GDP Measure Growth Rates**]
```{r}
#DPRatio vs GDP growth over time 
x = combined_data_DPRatio$Year
y1 = combined_data_DPRatio$DPRatio
y2 = combined_data_DPRatio$GDP_growth
plot(x, y1, type="b", pch=16, col="red", main="DPRatio vs GDP growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="DPRatio vs GDP", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("DPRatio", "GDP growth"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```

```{r}
#DPRatio vs NDG growth over time 
x = combined_data_DPRatio$Year
y1 = combined_data_DPRatio$DPRatio
y2 = combined_data_DPRatio$Nondurable.goods_growth
plot(x, y1, type="b", pch=16, col="red", main="DPRatio vs NDG growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="DPRatio vs NDG", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("DPRatio", "NDG growth"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```

```{r}
#DPRatio vs PCE growth over time 
x = combined_data_DPRatio$Year
y1 = combined_data_DPRatio$DPRatio
y2 = combined_data_DPRatio$Personal.consumption.expenditures_growth
plot(x, y1, type="b", pch=16, col="red", main="DPRatio vs PCE growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="DPRatio vs PCE", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("DPRatio", "PCE growth"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```


```{r}
#DPRatio vs GPDI growth over time 
x = combined_data_DPRatio$Year
y1 = combined_data_DPRatio$DPRatio
y2 = combined_data_DPRatio$Gross.private.domestic.investment_growth
plot(x, y1, type="b", pch=16, col="red", main="DPRatio vs GPDI growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Gross IPO vs GPDI", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("DPRatio", "GPDI growth"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```


```{r}
#Gross IPO vs GNP growth over time 
x = combined_data_DPRatio$Year
y1 = combined_data_DPRatio$DPRatio
y2 = combined_data_DPRatio$Gross.national.product_growth
plot(x, y1, type="b", pch=16, col="red", main="DPRatio vs GNP growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="DPRatio vs GNP", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("DPRatio", "GNP growth"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```




[**DPRatio over time vs various GDP Measures**]


```{r}
#DPRatio vs GDP over time 
x = combined_data_DPRatio$Year
y1 = combined_data_DPRatio$DPRatio
y2 = combined_data_DPRatio$GDP
plot(x, y1, type="b", pch=16, col="red", main="DPRatio vs GDP over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="DPRatio vs GDP", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("DPRatio", "GDP"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```

```{r}
#DPRatio vs NDG over time 
x = combined_data_DPRatio$Year
y1 = combined_data_DPRatio$DPRatio
y2 = combined_data_DPRatio$Nondurable.goods
plot(x, y1, type="b", pch=16, col="red", main="DPRatio vs NDG over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="DPRatio vs NDG", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("DPRatio", "NDG"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```

```{r}
#DPRatio vs PCE over time 
x = combined_data_DPRatio$Year
y1 = combined_data_DPRatio$DPRatio
y2 = combined_data_DPRatio$Personal.consumption.expenditures
plot(x, y1, type="b", pch=16, col="red", main="DPRatio vs PCE over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="DPRatio vs PCE", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("DPRatio", "PCE"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```


```{r}
#DPRatio vs GPDI over time 
x = combined_data_DPRatio$Year
y1 = combined_data_DPRatio$DPRatio
y2 = combined_data_DPRatio$Gross.private.domestic.investment
plot(x, y1, type="b", pch=16, col="red", main="DPRatio vs GPDI over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Gross IPO vs GPDI", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("DPRatio", "GPDI"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```


```{r}
#Gross IPO vs GNP over time 
x = combined_data_DPRatio$Year
y1 = combined_data_DPRatio$DPRatio
y2 = combined_data_DPRatio$Gross.national.product
plot(x, y1, type="b", pch=16, col="red", main="DPRatio vs GNP over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="DPRatio vs GNP", xlim=c(1960, 2015))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2005, 90, legend=c("DPRatio", "GNP"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```



```{r}
#Run correlation tests with equity premium, risk aversion measures and GDP growth rate measures
```




```{r}
#Run correlation tests between different GDP growth measures and gross IPO
#Years: 1960 to 2015
#Correlation with GNP growth rates
cor(combined_data_IPO_Gross$IPO_Gross, as.numeric(combined_data_IPO_Gross$Gross.national.product_growth))

#Correlation with GDP growth rates
cor(combined_data_IPO_Gross$IPO_Gross,  as.numeric(combined_data_IPO_Gross$GDP_growth))

#Correlation with GPDI growth rates
cor(combined_data_IPO_Gross$IPO_Gross, as.numeric(combined_data_IPO_Gross$Gross.private.domestic.investment_growth))

#Correlation with nondurable goods growth rates
cor(combined_data_IPO_Gross$IPO_Gross, as.numeric(combined_data_IPO_Gross$Nondurable.goods_growth))

#Correlation with personal consumption expenditures growth rates
cor(combined_data_IPO_Gross$IPO_Gross, as.numeric(combined_data_IPO_Gross$Personal.consumption.expenditures_growth))


```

```{r}
#Run correlation tests between different GDP growth measures and DPRatio
#Years: 1960 to 2015 (Full Data)
#Correlation with GNP
cor(combined_data_DPRatio$DPRatio, as.numeric(combined_data_DPRatio$Gross.national.product_growth))

#Correlation with GDP
cor(combined_data_DPRatio$DPRatio,  as.numeric(combined_data_DPRatio$GDP_growth))

#Correlation with GPDI
cor(combined_data_DPRatio$DPRatio, as.numeric(combined_data_DPRatio$Gross.private.domestic.investment_growth))

#Correlation with nondurable goods
cor(combined_data_DPRatio$DPRatio, as.numeric(combined_data_DPRatio$Nondurable.goods_growth))


#Correlation with personal consumption expenditures
cor(combined_data_DPRatio$DPRatio, as.numeric(combined_data_DPRatio$Personal.consumption.expenditures_growth))

```

```{r}
#Run correlation tests between different GDP growth measures and EPBound
#Years: 1960 to 2015
#Correlation with GNP
cor(combined_data_EPBound$EPBound, as.numeric(combined_data_EPBound$Gross.national.product_growth))

#Correlation with GDP
cor(combined_data_EPBound$EPBound,  as.numeric(combined_data_EPBound$GDP_growth))

#Correlation with GPDI
cor(combined_data_EPBound$EPBound, as.numeric(combined_data_EPBound$Gross.private.domestic.investment_growth))

#Correlation with nondurable goods
cor(combined_data_EPBound$EPBound, as.numeric(combined_data_EPBound$Nondurable.goods_growth))


#Correlation with personal consumption expenditures
cor(combined_data_EPBound$EPBound, as.numeric(combined_data_EPBound$Personal.consumption.expenditures_growth))

```

```{r}
#Run correlation tests between different GDP growth measures and PVS
#Years: 1960 to 2015
#Correlation with GNP
cor(as.numeric(combined_data_PVS$PVS), as.numeric(combined_data_PVS$Gross.national.product_growth))

#Correlation with GDP
cor(as.numeric(combined_data_PVS$PVS), as.numeric(combined_data_PVS$GDP_growth))

#Correlation with GPDI
cor(as.numeric(combined_data_PVS$PVS), as.numeric(combined_data_PVS$Gross.private.domestic.investment_growth))

#Correlation with nondurable goods
cor(as.numeric(combined_data_PVS$PVS), as.numeric(combined_data_PVS$Nondurable.goods_growth))


#Correlation with personal consumption expenditures
cor(as.numeric(combined_data_PVS$PVS), as.numeric(combined_data_PVS$Personal.consumption.expenditures_growth))

```



```{r}
#Run correlation tests between different GDP growth measures and Surplus Consumption Ratio
#Years: 1960 to 2015 
#Correlation with GNP
cor(combined_data_SCR$SCR, as.numeric(combined_data_SCR$Gross.national.product_growth))

#Correlation with GDP
cor(combined_data_SCR$SCR,  as.numeric(combined_data_SCR$GDP_growth))

#Correlation with GPDI
cor(combined_data_SCR$SCR, as.numeric(combined_data_SCR$Gross.private.domestic.investment_growth))

#Correlation with nondurable goods
cor(combined_data_SCR$SCR, as.numeric(combined_data_SCR$Nondurable.goods_growth))


#Correlation with personal consumption expenditures
cor(combined_data_SCR$SCR, as.numeric(combined_data_SCR$Personal.consumption.expenditures_growth))

```

```{r}
#Run correlation tests between different GDP growth measures and Aggregate Risk Aversion
#1990 to 2010
#Correlation with GNP
cor(combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion, as.numeric(combined_data_Aggregate_Risk_Aversion$Gross.national.product_growth))

#Correlation with GDP
cor(combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion,as.numeric(combined_data_Aggregate_Risk_Aversion$GDP_growth))

#Correlation with GPDI
cor(combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion, as.numeric(combined_data_Aggregate_Risk_Aversion$Gross.private.domestic.investment_growth))

#Correlation with nondurable goods
cor(combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion, as.numeric(combined_data_Aggregate_Risk_Aversion$Nondurable.goods_growth))


#Correlation with personal consumption expenditures
cor(combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion, as.numeric(combined_data_Aggregate_Risk_Aversion$Personal.consumption.expenditures_growth))

```

```{r}
#Run correlation tests between different GDP growth measures and UNE 
#Years: 1960 to 2015
#Correlation with GNP
cor(combined_data_UNE$UNE, as.numeric(combined_data_UNE$Gross.national.product_growth))

#Correlation with GDP
cor(combined_data_UNE$UNE, as.numeric(combined_data_UNE$GDP_growth))

#Correlation with GPDI
cor(combined_data_UNE$UNE, as.numeric(combined_data_UNE$Gross.private.domestic.investment_growth))

#Correlation with nondurable goods
cor(combined_data_UNE$UNE, as.numeric(combined_data_UNE$Nondurable.goods_growth))


#Correlation with personal consumption expenditures
cor(combined_data_UNE$UNE, as.numeric(combined_data_UNE$Personal.consumption.expenditures_growth))

```

```{r}
#create time series dates for all datasets
date_makers = function(yr, quart){
result <- c()
  if (quart ==  "Q1"){
    x <- paste(yr, '01','01', sep = "-")
    result <- x
  }
  else if (quart ==  "Q2"){
    x <- paste(yr, '04','01', sep = "-")
    result <- x
  }
  else if (quart ==  "Q3"){
    x <- paste(yr, '07','01', sep = "-")
    result <- x
  }
  else {
    x <- paste(yr, '10','01', sep = "-")
    result <- x
  }

return (result)
}



```


```{r}
#create date column in all datasets using date maker function
combined_data_IPO_Gross$Date = as.Date(mapply(date_makers, combined_data_IPO_Gross$Year,
                                           combined_data_IPO_Gross$Quarter))
combined_data_EPBound$Date = as.Date(mapply(date_makers, combined_data_EPBound$Year,
                                           combined_data_EPBound$Quarter))
combined_data_UNE$Date = as.Date(mapply(date_makers, combined_data_UNE$Year,
                                           combined_data_UNE$Quarter))
combined_data_DPRatio$Date = as.Date(mapply(date_makers, combined_data_DPRatio$Year,
                                           combined_data_DPRatio$Quarter))
combined_data_Aggregate_Risk_Aversion$Date = as.Date(mapply(date_makers, combined_data_Aggregate_Risk_Aversion$Year,
                                           combined_data_Aggregate_Risk_Aversion$Quarter))
combined_data_PVS$Date = as.Date(mapply(date_makers, combined_data_PVS$Year,
                                           combined_data_PVS$Quarter))
combined_data_SCR$Date = as.Date(mapply(date_makers, combined_data_SCR$Year,
                                           combined_data_SCR$Quarter))
```


```{r}
#Using the dates, create time series plots 
```


```{r}
#Start with Gross IPO


#Gross IPO vs GDP over time 
x = combined_data_IPO_Gross$Date
y1 = combined_data_IPO_Gross$IPO_Gross
y2 = combined_data_IPO_Gross$GDP
plot(x, y1, type="b", pch=16, col="red", main="Gross IPO vs GDP growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Gross IPO vs GDP")
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("Gross IPO", "GDP"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```


```{r}


#Gross IPO vs GNP over time 
x = combined_data_IPO_Gross$Date
y1 = combined_data_IPO_Gross$IPO_Gross
y2 = combined_data_IPO_Gross$Gross.national.product
plot(x, y1, type="b", pch=16, col="red", main="Gross IPO vs GNP growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Gross IPO vs GNP")
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("Gross IPO", "GNP"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```



```{r}


#Gross IPO vs PCE over time 
x = combined_data_IPO_Gross$Date
y1 = combined_data_IPO_Gross$IPO_Gross
y2 = combined_data_IPO_Gross$Personal.consumption.expenditures
plot(x, y1, type="b", pch=16, col="red", main="Gross IPO vs PCE growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Gross IPO vs PCE")
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("Gross IPO", "PCE"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")
```



```{r}


#Gross IPO vs GPDI over time 
x = combined_data_IPO_Gross$Date
y1 = combined_data_IPO_Gross$IPO_Gross
y2 = combined_data_IPO_Gross$Gross.private.domestic.investment
plot(x, y1, type="b", pch=16, col="red", main="Gross IPO vs GPDI growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Gross IPO vs GPDI")
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("Gross IPO", "GPDI"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```


```{r}


#Gross IPO vs PCE over time 
x = combined_data_IPO_Gross$Date
y1 = combined_data_IPO_Gross$IPO_Gross
y2 = combined_data_IPO_Gross$Nondurable.goods
plot(x, y1, type="b", pch=16, col="red", main="Gross IPO vs nondurable goods growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="Gross IPO vs Nondurable Goods")
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("Gross IPO", "Nondurable goods"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```










```{r}
#Next EP Bound


#EPBound vs GDP over time 
x = combined_data_EPBound$Date
y1 = combined_data_EPBound$EPBound * 10
y2 = combined_data_EPBound$GDP
plot(x, y1, type="b", pch=16, col="red", main="EPBound (Red) scaled by 10 vs GDP growth over time, 1996 - 2011", sub="1996-2011",
  xlab="Year", ylab="EPBound vs GDP", ylim= c(-1, 5))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("EPBound", "GDP"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```


```{r}


#EPBound vs GNP over time 
x = combined_data_EPBound$Date
y1 = combined_data_EPBound$EPBound * 10
y2 = combined_data_EPBound$Gross.national.product
plot(x, y1, type="b", pch=16, col="red", main="EPBound (Red) scaled by 10 vs GNP growth over time, 1996 - 2011", sub="1996-2011",
  xlab="Year", ylab="EPBound vs GNP", ylim= c(-1, 5))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("EPBound", "GNP"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```

```{r}


#EPBound vs PCE over time 
x = combined_data_EPBound$Date
y1 = combined_data_EPBound$EPBound * 10
y2 = combined_data_EPBound$Personal.consumption.expenditures
plot(x, y1, type="b", pch=16, col="red", main="EPBound (Red) scaled by 10 vs PCE growth over time, 1996 - 2011", sub="1996-2011",
  xlab="Year", ylab="EPBound vs PCE", ylim= c(-7, 6))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("EPBound", "PCE"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```



```{r}


#EPBound vs GPDI over time 
x = combined_data_EPBound$Date
y1 = combined_data_EPBound$EPBound * 10
y2 = combined_data_EPBound$Gross.private.domestic.investment
plot(x, y1, type="b", pch=16, col="red", main="EPBound (Red) scaled by 10 vs GPDI growth over time, 1996 - 2011", sub="1996-2011",
  xlab="Year", ylab="EPBound vs GPDI", ylim= c(-7, 8))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2000, 0, legend=c("EPBound", "GPDI"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```





```{r}


#EPBound vs Nondurable Goods over time 
x = combined_data_EPBound$Date
y1 = combined_data_EPBound$EPBound * 10
y2 = combined_data_EPBound$Nondurable.goods
plot(x, y1, type="b", pch=16, col="red", main="EPBound (Red) scaled by 10 vs NDG's growth over time, 1996 - 2011", sub="1996-2011",
  xlab="Year", ylab="EPBound vs Nondurable Goods", ylim= c(-25, 15))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(2000, 0, legend=c("EPBound", "Nondurable Goods"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```




```{r}
#DPRatio vs GDP over time 
x = combined_data_DPRatio$Date
y1 = combined_data_DPRatio$DPRatio * 100
y2 = combined_data_DPRatio$GDP
plot(x, y1, type="b", pch=16, col="red", main="DPRatio (red, scaled by 100) vs GDP growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="DPRatio vs GDP", ylim = c(-1, 15))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("DPRatio", "GDP"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```



```{r}
#DPRatio vs GNP over time 
x = combined_data_DPRatio$Date
y1 = combined_data_DPRatio$DPRatio * 100
y2 = combined_data_DPRatio$Gross.national.product
plot(x, y1, type="b", pch=16, col="red", main="DPRatio (red, scaled by 100) vs GNP growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="DPRatio vs GNP", ylim = c(-1, 15))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("DPRatio", "GNP"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```



```{r}
#DPRatio vs PCE over time 
x = combined_data_DPRatio$Date
y1 = combined_data_DPRatio$DPRatio * 100
y2 = combined_data_DPRatio$Personal.consumption.expenditures
plot(x, y1, type="b", pch=16, col="red", main="DPRatio (red, scaled by 100) vs PCE growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="DPRatio vs PCE", ylim = c(-10, 15))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("DPRatio", "PCE"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```



```{r}
#DPRatio vs NDG over time 
x = combined_data_DPRatio$Date
y1 = combined_data_DPRatio$DPRatio * 100
y2 = combined_data_DPRatio$Nondurable.goods
plot(x, y1, type="b", pch=16, col="red", main="DPRatio (red, scaled by 100) vs NDG growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="DPRatio vs NDG", ylim = c(-25, 25))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("DPRatio", "NDG"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```


```{r}
#DPRatio vs GPDI over time 
x = combined_data_DPRatio$Date
y1 = combined_data_DPRatio$DPRatio * 100
y2 = combined_data_DPRatio$Gross.private.domestic.investment
plot(x, y1, type="b", pch=16, col="red", main="DPRatio (red, scaled by 100) vs GPDI growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="DPRatio vs GPDI", ylim = c(-10, 20))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("DPRatio", "GPDI"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```




```{r}
#PVS vs GDP over time 
x = combined_data_PVS$Date
y1 = combined_data_PVS$PVS
y2 = combined_data_PVS$GDP
plot(x, y1, type="b", pch=16, col="red", main="PVS (Red) vs GPD growth over time, 1970 - 2015", sub="1970-2015",
  xlab="Year", ylab="PVS vs GPD", ylim = c(-2, 15))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("PVS", "GPD"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```



```{r}
#PVS vs GNP over time 
x = combined_data_PVS$Date
y1 = combined_data_PVS$PVS
y2 = combined_data_PVS$GDP
plot(x, y1, type="b", pch=16, col="red", main="PVS (Red) vs GNP growth over time, 1970 - 2015", sub="1970-2015",
  xlab="Year", ylab="PVS vs GNP", ylim = c(-2, 15))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("PVS", "GNP"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```


```{r}
#PVS vs PCE over time 
x = combined_data_PVS$Date
y1 = combined_data_PVS$PVS
y2 = combined_data_PVS$Personal.consumption.expenditures
plot(x, y1, type="b", pch=16, col="red", main="PVS (Red) vs PCE growth over time, 1970 - 2015", sub="1970-2015",
  xlab="Year", ylab="PVS vs PCE", ylim = c(-10, 15))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("PVS", "PCE"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```

```{r}
#PVS vs NDG over time 
x = combined_data_PVS$Date
y1 = combined_data_PVS$PVS
y2 = combined_data_PVS$Nondurable.goods
plot(x, y1, type="b", pch=16, col="red", main="PVS (Red) vs NDG growth over time, 1970 - 2015", sub="1970-2015",
  xlab="Year", ylab="PVS vs NDG", ylim = c(-25, 25))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("PVS", "NDG"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```

```{r}
#PVS vs GPDI over time 
x = combined_data_PVS$Date
y1 = combined_data_PVS$PVS
y2 = combined_data_PVS$Gross.private.domestic.investment
plot(x, y1, type="b", pch=16, col="red", main="PVS (Red) vs GPDI growth over time, 1970 - 2015", sub="1970-2015",
  xlab="Year", ylab="PVS vs GPDI", ylim = c(-10, 17))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("PVS", "GPDI"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```







```{r}
#SCR vs GDP over time 
x = combined_data_SCR$Date
y1 = combined_data_SCR$SCR * 100
y2 = combined_data_SCR$GDP
plot(x, y1, type="b", pch=16, col="red", main="SCR (Scaled by 100, Red) vs GDP growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="SCR vs GDP", ylim = c(-2, 15))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("SCR", "GDP"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```

```{r}
#SCR vs GNP over time 
x = combined_data_SCR$Date
y1 = combined_data_SCR$SCR * 100
y2 = combined_data_SCR$Gross.national.product
plot(x, y1, type="b", pch=16, col="red", main="SCR (Scaled by 100, Red) vs GNP growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="SCR vs GNP", ylim = c(-2, 15))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("SCR", "GNP"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```

```{r}
#SCR vs NDG over time 
x = combined_data_SCR$Date
y1 = combined_data_SCR$SCR * 100
y2 = combined_data_SCR$Nondurable.goods
plot(x, y1, type="b", pch=16, col="red", main="SCR (Scaled by 100, Red) vs NDG growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="SCR vs NDG", ylim = c(-25, 25))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("SCR", "NDG"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")
```



```{r}
#SCR vs GPDI over time 
x = combined_data_SCR$Date
y1 = combined_data_SCR$SCR * 100
y2 = combined_data_SCR$Gross.private.domestic.investment
plot(x, y1, type="b", pch=16, col="red", main="SCR (Scaled by 100, Red) vs GPDI growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="SCR vs GPDI", ylim = c(-10, 20))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("SCR", "GPDI"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")
```

```{r}
#SCR vs GPDI over time 
x = combined_data_SCR$Date
y1 = combined_data_SCR$SCR * 100
y2 = combined_data_SCR$Personal.consumption.expenditures
plot(x, y1, type="b", pch=16, col="red", main="SCR (Scaled by 100, Red) vs PCE growth over time, 1960 - 2015", sub="1960-2015",
  xlab="Year", ylab="SCR vs PCE", ylim = c(-10, 15))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("SCR", "PCE"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")
```

```{r}
#Aggregate_Risk_Aversion vs GDP over time 
x = combined_data_Aggregate_Risk_Aversion$Date
y1 = combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion
y2 = combined_data_Aggregate_Risk_Aversion$GDP
plot(x, y1, type="b", pch=16, col="red", main="Aggregate_Risk_Aversion (Red) vs GDP growth over time, 1990 - 2010", sub="1990-2010",
  xlab="Year", ylab="Aggregate_Risk_Aversionvs GDP", ylim = c(-2, 15))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("Aggregate_Risk_Aversion", "GDP"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```

```{r}
#Aggregate_Risk_Aversion vs GNP over time 
x = combined_data_Aggregate_Risk_Aversion$Date
y1 = combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion
y2 = combined_data_Aggregate_Risk_Aversion$Gross.national.product
plot(x, y1, type="b", pch=16, col="red", main="Aggregate_Risk_Aversion (Red) vs GNP growth over time, 1990 - 2010", sub="1990-2010",
  xlab="Year", ylab="Aggregate_Risk_Aversionvs GNP", ylim = c(-2, 15))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("Aggregate_Risk_Aversion", "GNP"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```

```{r}
#Aggregate_Risk_Aversion vs PCE over time 
x = combined_data_Aggregate_Risk_Aversion$Date
y1 = combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion
y2 = combined_data_Aggregate_Risk_Aversion$Personal.consumption.expenditures
plot(x, y1, type="b", pch=16, col="red", main="Aggregate_Risk_Aversion (Red) vs PCE growth over time, 1990 - 2010", sub="1990-2010",
  xlab="Year", ylab="Aggregate_Risk_Aversion vs PCE", ylim = c(-8, 8))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("Aggregate_Risk_Aversion", "PCE"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```


```{r}
#Aggregate_Risk_Aversion vs NDG over time 
x = combined_data_Aggregate_Risk_Aversion$Date
y1 = combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion
y2 = combined_data_Aggregate_Risk_Aversion$Nondurable.goods
plot(x, y1, type="b", pch=16, col="red", main="Aggregate_Risk_Aversion (Red) vs NDG growth over time, 1990 - 2010", sub="1990-2010",
  xlab="Year", ylab="Aggregate_Risk_Aversion vs NDG", ylim = c(-25, 15))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("Aggregate_Risk_Aversion", "NDG"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```



```{r}
#Aggregate_Risk_Aversion vs GPDI over time 
x = combined_data_Aggregate_Risk_Aversion$Date
y1 = combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion
y2 = combined_data_Aggregate_Risk_Aversion$Gross.private.domestic.investment
plot(x, y1, type="b", pch=16, col="red", main="Aggregate_Risk_Aversion (Red) vs GPDI growth over time, 1990 - 2010", sub="1990-2010",
  xlab="Year", ylab="Aggregate_Risk_Aversion vs GPDI", ylim = c(-10, 10))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("Aggregate_Risk_Aversion", "GPDI"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```


```{r}
#UNE vs GDP over time 
x = combined_data_UNE$Date
y1 = combined_data_UNE$UNE
y2 = combined_data_UNE$GDP
plot(x, y1, type="b", pch=16, col="red", main="UNE (Red) vs GDP growth over time, 1960 - 2015", sub="1960 - 2015",
  xlab="Year", ylab="UNE vs GDP", ylim = c(-2, 15))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("UNE", "GDP"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```


```{r}
#UNE vs GNP over time 
x = combined_data_UNE$Date
y1 = combined_data_UNE$UNE
y2 = combined_data_UNE$Gross.national.product
plot(x, y1, type="b", pch=16, col="red", main="UNE (Red) vs GNP growth over time, 1960 - 2015", sub="1960 - 2015",
  xlab="Year", ylab="UNE vs GNP", ylim = c(-2, 15))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("UNE", "GNP"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```


```{r}
#UNE vs NDG over time 
x = combined_data_UNE$Date
y1 = combined_data_UNE$UNE
y2 = combined_data_UNE$Nondurable.goods
plot(x, y1, type="b", pch=16, col="red", main="UNE (Red) vs NDG growth over time, 1960 - 2015", sub="1960 - 2015",
  xlab="Year", ylab="UNE vs NDG", ylim = c(-25, 25))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("UNE", "NDG"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```



```{r}
#UNE vs PCE over time 
x = combined_data_UNE$Date
y1 = combined_data_UNE$UNE
y2 = combined_data_UNE$Personal.consumption.expenditures
plot(x, y1, type="b", pch=16, col="red", main="UNE (Red) vs PCE growth over time, 1960 - 2015", sub="1960 - 2015",
  xlab="Year", ylab="UNE vs PCE", ylim = c(-10, 15))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("UNE", "PCE"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```




```{r}
#UNE vs GPDI over time 
x = combined_data_UNE$Date
y1 = combined_data_UNE$UNE
y2 = combined_data_UNE$Gross.private.domestic.investment
plot(x, y1, type="b", pch=16, col="red", main="UNE (Red) vs GPDI growth over time, 1960 - 2015", sub="1960 - 2015",
  xlab="Year", ylab="UNE vs GPDI", ylim = c(-10, 17))
# Add lines for gdp measures
lines(x, y2, pch=18, col="blue", type="b", lty=2)
legend(-3800, 97, legend=c("UNE", "GPDI"),
       col=c("red", "blue"), lty=1:1, cex=0.8) + 
theme(legend.position="top")

```





```{r}
#install package needed for lead/lag correlation
#if(!require('YRmisc')) {
 # install.packages('YRmisc')
  library('YRmisc')
#}
```

```{r}
#lead lag with gross ipo, lead/lag by 3 quarters
cor.lag(as.numeric(combined_data_IPO_Gross$IPO_Gross), as.numeric(combined_data_IPO_Gross$GDP), 3,3)
cor.lag(as.numeric(combined_data_IPO_Gross$IPO_Gross), as.numeric(combined_data_IPO_Gross$Gross.national.product), 3,3)
cor.lag(as.numeric(combined_data_IPO_Gross$IPO_Gross), as.numeric(combined_data_IPO_Gross$Gross.private.domestic.investment), 3,3)
cor.lag(as.numeric(combined_data_IPO_Gross$IPO_Gross), as.numeric(combined_data_IPO_Gross$Nondurable.goods), 3,3)
cor.lag(as.numeric(combined_data_IPO_Gross$IPO_Gross), as.numeric(combined_data_IPO_Gross$Personal.consumption.expenditures), 3,3)
```


```{r}
#lead lag with EPBound, lead/lag by 3 quarters
cor.lag(as.numeric(combined_data_EPBound$EPBound), as.numeric(combined_data_EPBound$GDP), 3,3)
cor.lag(as.numeric(combined_data_EPBound$EPBound), as.numeric(combined_data_EPBound$Gross.national.product), 3,3)
cor.lag(as.numeric(combined_data_EPBound$EPBound), as.numeric(combined_data_EPBound$Gross.private.domestic.investment), 3,3)
cor.lag(as.numeric(combined_data_EPBound$EPBound), as.numeric(combined_data_EPBound$Nondurable.goods), 3,3)
cor.lag(as.numeric(combined_data_EPBound$EPBound), as.numeric(combined_data_EPBound$Personal.consumption.expenditures), 3,3)

```



```{r}
#lead lag with DPRatio, lead/lag by 3 quarters
cor.lag(as.numeric(combined_data_DPRatio$DPRatio), as.numeric(combined_data_DPRatio$GDP), 3,3)
cor.lag(as.numeric(combined_data_DPRatio$DPRatio), as.numeric(combined_data_DPRatio$Gross.national.product), 3,3)
cor.lag(as.numeric(combined_data_DPRatio$DPRatio), as.numeric(combined_data_DPRatio$Gross.private.domestic.investment), 3,3)
cor.lag(as.numeric(combined_data_DPRatio$DPRatio), as.numeric(combined_data_DPRatio$Nondurable.goods), 3,3)
cor.lag(as.numeric(combined_data_DPRatio$DPRatio), as.numeric(combined_data_DPRatio$Personal.consumption.expenditures), 3,3)
```


```{r}
#lead lag with Surplus Consumption Ratio, lead/lag by 3 quarters 
cor.lag(as.numeric(combined_data_SCR$SCR), as.numeric(combined_data_SCR$GDP),3,3)
cor.lag(as.numeric(combined_data_SCR$SCR), as.numeric(combined_data_SCR$Gross.national.product), 3,3)
cor.lag(as.numeric(combined_data_SCR$SCR), as.numeric(combined_data_SCR$Gross.private.domestic.investment), 3,3)
cor.lag(as.numeric(combined_data_SCR$SCR), as.numeric(combined_data_SCR$Nondurable.goods), 3,3)
cor.lag(as.numeric(combined_data_SCR$SCR), as.numeric(combined_data_SCR$Personal.consumption.expenditures), 3,3)

```



```{r}
#lead lag with PVS, lead/lag by 3 quarters
cor.lag(as.numeric(combined_data_PVS$PVS), as.numeric(combined_data_PVS$GDP), 3,3)
cor.lag(as.numeric(combined_data_PVS$PVS), as.numeric(combined_data_PVS$Gross.national.product), 3,3)
cor.lag(as.numeric(combined_data_PVS$PVS), as.numeric(combined_data_PVS$Gross.private.domestic.investment), 3,3)
cor.lag(as.numeric(combined_data_PVS$PVS), as.numeric(combined_data_PVS$Nondurable.goods), 3,3)
cor.lag(as.numeric(combined_data_PVS$PVS), as.numeric(combined_data_PVS$Personal.consumption.expenditures), 3,3)
```


```{r}
#lead lag with Aggregate Risk Aversion, lead/lag by 3 quarters 
cor.lag(as.numeric(combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion), as.numeric(combined_data_Aggregate_Risk_Aversion$GDP), 3,3)
cor.lag(as.numeric(combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion), as.numeric(combined_data_Aggregate_Risk_Aversion$Gross.national.product), 3,3)
cor.lag(as.numeric(combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion), as.numeric(combined_data_Aggregate_Risk_Aversion$Gross.private.domestic.investment), 3,3) 

cor.lag(as.numeric(combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion),
as.numeric(combined_data_Aggregate_Risk_Aversion$Nondurable.goods), 3,3)


cor.lag(as.numeric(combined_data_Aggregate_Risk_Aversion$Aggregate_Risk_Aversion), as.numeric(combined_data_Aggregate_Risk_Aversion$Personal.consumption.expenditures), 3,3)

```


```{r}
#lead lag with UNE, lead/lag by 3 quarters 
cor.lag(as.numeric(combined_data_UNE$UNE), as.numeric(combined_data_UNE$GDP), 3,3)
cor.lag(as.numeric(combined_data_UNE$UNE), as.numeric(combined_data_UNE$Gross.national.product), 3,3)
cor.lag(as.numeric(combined_data_UNE$UNE), as.numeric(combined_data_UNE$Gross.private.domestic.investment), 3,3)
cor.lag(as.numeric(combined_data_UNE$UNE), as.numeric(combined_data_UNE$Nondurable.goods), 3,3)
cor.lag(as.numeric(combined_data_UNE$UNE), as.numeric(combined_data_UNE$Personal.consumption.expenditures), 3,3)

```














